### ISSUE TITLE
Move code to C++

### ISSUE THREAD

**Issue by rodluger** [rodluger/starry#1]
The code is currently pretty slow since I've put zero effort into optimizing it. I plan to switch it over to C/C++ and use something like ctypes to interface with Python.

**Comment by dfm** [comment]
Cool. I'd recommend using pybind11 instead of ctypes. It has a lot of nice features that'll make it easier to debug and maintain. Happy to help there!

**Comment by rodluger** [comment]
Working on coding things up in the starry/cpp directory.

**Comment by rodluger** [comment]
Code works and is somewhat benchmarked. I tried getting pybind11 to work but failed miserably. I'm going to code it up with ctypes now so I can get it talking to my Python routines, but @dfm feel free to switch it over to pybind11 when you get a chance.

**Comment by rodluger** [comment]
Done!
