### ISSUE TITLE
Determine when to do upward / downward recursion

### ISSUE THREAD

**Issue by rodluger** [rodluger/starry#104]
In the computation of `J_v`, I am currently doing upward recursion when `0.5 < k^2 < 2.0` and downward recursion in all other cases. This seems to work well in all the cases I've tested, but I'm opening this issue so that we can re-visit this at some point with some more rigorous stability tests.

**Comment by rodluger** [comment]
@ericagol Did you find that the tridiagonal solver improved the stability of the code? Is it worth coding up in C?

**Comment by ericagol** [comment]
It didn't seem to for the couple of cases that I tried, but I didn't test it widely.

**Comment by rodluger** [comment]
OK. I'm going to close this issue for now. The one thing I *did* have to implement is when `l` is very large (typically > 15 or so) the downward recursion for `J` begins to cause instabilities for `J_v` when `v` is small (since we're doing so many operations to get down to zero). It's not a big deal, but it decreases our precision from `ppb` to `~ppm`. So if `l` is very large, I actually compute `J_v` and `J_{v - 1}` at both `v = vmax` and `v = vmax / 2`. This stabilizes the low `v` cases, just like the tridiagonal solver would.
