### ISSUE TITLE
`cel` does not converge in the limit `b - r = 1`

### ISSUE THREAD

**Issue by rodluger** [rodluger/starry#108]
This is a pathological case, but for large occultors, `cel` does not converge when `b > r + 1 - 1e-12`. We might need to enforce a hard boundary here to prevent the program from crashing.
On the **dev** branch:
```python
>>>import starry
>>>map = starry.Map()
>>>map[1, 0] = 1
>>>ro = 100
>>>map.flux(ro=ro, yo=0, xo=ro + 1 - 1e-12)
RuntimeError: Elliptic integral CEL did not converge.
```

**Comment by ericagol** [comment]
@rodluger  Don't you use downward iteration for `I_v` and `J_v` in this case?   Or is it `s_2` which is causing the problem?

**Comment by ericagol** [comment]
@rodluger My version seems to work fine if I use `IJv_lower`, but I did find that when `b = r + 1 - 1e-15` that `k2=0`.  This causes the `I_v` and `J_v` integrals to go to zero, but a division by `k^2` in the routines causes `NaN` values.  So, before those routines are called, I now check to see whether `k^2 > 0`.

**Comment by rodluger** [comment]
I get the error when computing s2. Does that not happen for you?

**Comment by ericagol** [comment]
@rodluger No, I don't.  The following line:
 
`julia> include("s2_stable.jl"); r=100.0; b=r+1-1e-12; s2(r,b)`

returns

`1.0`

**Comment by rodluger** [comment]
I think I understand what the difference is. There's no `eps(x)` function for arbitrary `x` in C++, but there is the equivalent of `eps(1)`. I've been approximating `eps(x) ~ eps(1) * x`, which I think is fine, except when `x = 0`, which is the limit I'm hitting here. My tolerance is then identically zero and the integral never converges. I can just set a lower limit on the tolerance to fix this.
