### ISSUE TITLE
Better `minimize` method

### ISSUE THREAD

**Issue by rodluger** [rodluger/starry#109]
Currently, the `minimize` method of a map finds the minimum of the specific intensity (useful for ensuring the maps are positive semi-definite) by calling `scipy.minimize`, which is really dumb. @dfm and @dflemin3 do you know of any good/portable C++ libraries/functions for doing minimization? Ideally, something that allows for constrained minimization: minimize `I(x, y, z)` along the surface `x^2 + y^2 + z^2 = 1`, or re-parametrize and solve `I(x, y)` for `x^2 + y^2 <= 1`.

**Comment by rodluger** [comment]
Note that the first two cases are easy, and we should code them up separately:
- For degree `l = 0` maps, the constraint is trivial: `y_0 >= 0`.
- For degree `l = 1` maps, we worked out that we need `y_1^2 + y_2^2 + y_3^2 <= y_0^2 / 3`.

I suspect there may be an analytic solution to `l = 2`, but I haven't been able to find one. We need to find the minimum of
![image](https://user-images.githubusercontent.com/9323819/41549208-ef6e7988-72d9-11e8-90ca-0f117ee9bbc3.png)
with `z = +/- sqrt(1 - x^2 - y^2)`. There should be a way to write the expression for the minimum as a polynomial, but I get a bunch of mixed terms involving powers of `x` and `y` and square roots. @ericagol, any insights into whether this might have an analytic solution?

**Comment by ericagol** [comment]
@rodluger What are the `y_0` ... `y_8` constants?

**Comment by rodluger** [comment]
I call the vector of spherical harmonic coefficients `y` (for the `s^T A R R y` pun to work).

**Comment by ericagol** [comment]
Maybe this will help:  https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4360959/

**Comment by rodluger** [comment]
Nice! That does look super useful. Finding the minimum in spherical coordinates avoids the square roots. I'll dig into it.

**Comment by ericagol** [comment]
HEALPix can find extrema through a nearest-neighbor search, but I think this is probably overkill for your purposes (it would involve pixellating the sphere):  https://arxiv.org/abs/astro-ph/9803317

**Comment by rodluger** [comment]
@ericagol At one point you mentioned we might be able to inspect the magnitudes of the coefficients of a map at a given degree to infer whether the map is positive semi-definite. That is, a criterion that, if met, guarantees the map is non-negative everywhere (but not one that all positive semi-definite maps must meet, since *that's* not analytic).

One way to do this, I think, is to sum the maximum values of all spherical harmonics, weighted by their coefficients (with absolute values taken as needed). If that sum is less than `Y_{0,0}`, the map *has* to be positive semi-definite.

If we look at the spherical harmonics,
![image](https://user-images.githubusercontent.com/9323819/41863348-504888f8-785b-11e8-89db-1eb45bae3178.png)
we note that the `m < 0` ones are just rotations of the `m>= 0` ones, so we can consider only the latter. The maxima of these occur along the `x` axis, where `phi = 0` and `Y = +/-P_{lm}`; i.e., the value of the spherical harmonic along this axis is just the value of the corresponding [associated Legendre function](https://en.wikipedia.org/wiki/Associated_Legendre_polynomials), which are just simple polynomials times powers of `sqrt(1 - x^2)`. So our problem boils down to finding the maxima of the Legendre functions. But I can't figure out how to do that. There are nice recursion relations for the derivatives, but solving for the maximum still does not look to be analytic...

**Comment by rodluger** [comment]
OK, yes, but no rush. I just implemented a simple LBFGS algorithm on the C++ side to quickly find the minimum. Still nonlinear, but *much* faster than my previous approach, which wrapped `scipy`.

**Comment by rodluger** [comment]
My LBFGS solver seems to have worked.
