### ISSUE TITLE
Derivative stability issues

### ISSUE THREAD

**Issue by ericagol** [rodluger/starry#113]
@rodluger For Figure 10 (p. 26), the `r=0.01` case should have a range of impact parameter that extends from `b=0` to `b=1+r`.

**Comment by rodluger** [comment]
That's a good point. My code doesn't care whether `b` is positive or negative, so there's nothing technically wrong with the figure, but there are regions that are plotted twice. But it makes a lot more sense to start at zero. Will do.

**Comment by ericagol** [comment]
I think the regions to focus on are near `0`, `r`, `1-r`, `r`, and `1+r`.

**Comment by ericagol** [comment]
I tried making a similar plot for the derivatives, but unfortunately there appear to be significant errors in computing the derivatives during ingress/egress for both `r=0.01` and `r=100`.  I'm getting `NaN` values as well differences between the finite difference `BigFloat` derivatives and the autodiff derivatives.  I haven't implemented the `cel` analytic derivatives yet;  perhaps that will help.  Or perhaps I'm making an error somewhere.

**Comment by ericagol** [comment]
In the `r=100` case, the derivative errors are occurring most often for `n` doubly even, just after the start and just before the end of ingress/egress.  In all of these cases, if I set `Q` to zero, the error disappears.  So, it may be worth investigating a bit further how to stably compute `H_{uv}`.

**Comment by rodluger** [comment]
Interesting. I fixed figure 10. My Latex build on Travis is currently broken, so it might take a few hours for me to get the paper updated online. I'm changing the title of this thread to focus on derivatives.

**Comment by rodluger** [comment]
What happens if you set P to zero? Is the instability in Q or in the difference Q - P?

**Comment by ericagol** [comment]
@rodluger Ah, good question.  When I set `P` to zero, the same error occurs.

**Comment by ericagol** [comment]
@rodluger I think I may have figured out a fix for this.  The problem seems to occur for `\lambda` near `\pi/2`.  If I define `\gamma = \lambda - \pi/2`, and then transform `\varphi` to `\varphi^\prime = \varphi-\pi/2`, then `H_{uv}` can be defined in terms of the sum of two integrals, one from `0` to `2\pi`, and another from `-\gamma` to `\gamma`, where `\gamma` is small.  The first integral can be done analytically in terms of `\Gamma` functions, while the second can be computed iteratively.

**Comment by rodluger** [comment]
Cool! Are you thinking this can replace H_{u,v} entirely in the paper?

**Comment by ericagol** [comment]
@rodluger We'll see if it works - it will probably be like the `I_v` case where the analog to `k^2` for `H_{uv}` is stable when it is close to one (this parameter is given by `((b+1)^2-r^2)/(4b)`, which is also greater than one when `b+r <1` and less than one when `b+r>1`), and we'll need an alternate expression when it is too large or small.

**Comment by ericagol** [comment]
@rodluger 

Okay, this took longer to figure out than I had hoped, but it turns out there a three simple changes to make which seems to mostly fix this problem (and, in hind sight, perhaps it could have fixed the `I_{uv}` problem):

1).  I find it more numerically stable to evaluate `\lambda` from the following expression:

![image](https://user-images.githubusercontent.com/243664/41690379-1627bbe4-74aa-11e8-99e1-081325a9e221.jpeg)

`\lambda = \cos^{-1}\frac{\sqrt{(1-(b-r)^2)((b+r)^2-1)}}{2b}`

and when `\lambda > \pi/2`, I subtract `\pi` to have `-\pi/2 <= \lambda <= \pi/2`.

2).  I evaluate `H_{u,1}` (i.e. with `v=1`) as:

![image](https://user-images.githubusercontent.com/243664/41690180-2c7850f8-74a9-11e8-812e-eacdeadf97d4.jpeg)

where, of course, `\cos{\lambda}` is evaluated from the analytic expression above.

`H_{u,1} = -\frac{2}{u+1}(\cos{\lambda})^{u+1}`

3).  For each `u >= 2`,  I evaluate `H_{u,v}` via the recursion expression for `v` rather than for `u`.  I originally evaluated the recursion in `u` given that both terms are positive in equation (D29).  However, it turns out that these tend to have opposite sign and cancel, which causes the numerical round-off error for odd values of `v`.  So, by evaluating the `v=1` analytically, and then iterating on `v`, this avoids the cancellation error.

All to say:  I think we can stick with the same formulae for `H_{uv}` that are in the paper right now.
However, I'm not achieving machine precision, although I am achieving about square root of it:

![sn_derivative_error_lmax_10](https://user-images.githubusercontent.com/243664/41691936-2a590476-74b2-11e8-8087-1f81cf47f4a1.png)

These are the errors for `r=0.01` (left) and `r=100` (right) for `l` up to 10, and for derivatives with respect to both `b` and `r` (sorry, I couldn't figure out your color scheme).   Interestingly, some of the largest errors are for `l=1` and `l=2`, so part of the problem is with the `s_2` derivative:  even though `s_2` is being computed to machine precision, this does not guarantee that the automatic derivative will also be machine precision.

Corollary: this approach might have stabilized the computation of `I_{uv}` as well, but now that we've derived the other expressions, it may not be worth going back to this approach.

I noticed in this process that when I call my code with `r=b`, it returns `NaN` values.
The julia code `sn_bigr.jl` also breaks when I call it with `b=0`.  These are still bugs to fix.

**Comment by rodluger** [comment]
@ericagol Awesome, thank you for looking into this. I will implement these changes in my code and write a script to generate derivative stability plots.

**Comment by ericagol** [comment]
Some of the derivatives are rather large, so I did use the `asinh` differences for the comparison (with the transition at 1).

**Comment by ericagol** [comment]
@rodluger I'm looking into the errors on the `s_2` derivative, and one thing I'm finding is that the derivative errors grow as we approach `b=r` and as we approach `b=r` and `b=1-r` for `r<1`.   I'm wondering whether this means that we should revert back to using an expansion near these special cases.  This plots computes as close as `10^{-14}` to each of these limits, and you can see that the `ds_2/dr` and `ds_2/db` errors grow substantially (left is `r=0.01` and right is `r=100`).

![s2_derivative_error](https://user-images.githubusercontent.com/243664/41739916-6d16c93a-754b-11e8-8592-f07f4f2c958a.png)

**Comment by ericagol** [comment]
@rodluger I'm differentiating the original `\Lambda` expression, and it turns out that the derivatives do not depend on `\Pi(n,k^2)` at all!  This means we should be able to evaluate the derivatives with `p=1`.  I think this agrees with Pál's appendix.

**Comment by ericagol** [comment]
@rodluger This turned out to be much easier than I expected!

Here are the expressions (courtesy of Mathematica):

![image](https://user-images.githubusercontent.com/243664/41783161-136bc858-75f1-11e8-9353-cf5e1cd07222.jpeg)

`\frac{\partial \Lambda}{\partial r} &= \frac{8br^2 E(k^2) + 2r(1-(b+r)^2)K(k^2)}{\pi\sqrt{br}}\\
\frac{\partial \Lambda}{\partial b} &= \frac{4r^2 E(k^2) - 2r(b+r)K(k^2)}{\pi\sqrt{br}}\\
\frac{\partial \Lambda}{\partial r} &= \frac{4r}{\pi}\sqrt{1-(b-r)^2} E(k^{-2})\\
\frac{\partial \Lambda}{\partial b} &= \frac{2}{3b\pi}\sqrt{1-(b-r)^2}\left[(r^2+b^2-1) E(k^{-2}) +(1-(b+r)^2)K(k^{-2})\right]`

The first two are for `k^2 <1`, `b+r >1`, and the latter two for `k^2 >1`, `b+r < 1`.  Of course, all of this could have been gleaned from the Pál (2008) paper.

These should be straightforward to transform to `cel` notation.

**Comment by rodluger** [comment]
Fantastic!!!

**Comment by ericagol** [comment]
I suspect so.  There is a division by `\sqrt{br}`, and evaluation of `K(1)`, but it may be that the `cel` version is stable.

**Comment by rodluger** [comment]
But the division by `\sqrt{br}` is only for `b + r > 1`, so it's unstable only when `r --> 0`, not `b --> 0`

**Comment by ericagol** [comment]
Wow, this works well!  I had to put a floor in the figure of `10^{-18}` since most of the derivative differences were zero.  This is a comparison between these analytic formulae and a `BigFloat` numerical finite difference computation.  Left is `r=0.01`, right is `r=100`.

![s2_derivative_error_analytic](https://user-images.githubusercontent.com/243664/41804237-c190e94e-7647-11e8-8469-667d5e8325ed.png)

**Comment by ericagol** [comment]
Here is the above plot of the errors of `s_n`, but now with `s_2` replaced with analytic derivative.

![sn_derivative_error_lmax_10](https://user-images.githubusercontent.com/243664/41804427-43056920-764b-11e8-948a-4e2f678bd0da.png)

It looks like there could be some room for improvement on the errors of the `s_n` derivative, but overall the results look pretty good!

**Comment by ericagol** [comment]
Not so fast...  I was using `\epsilon = 10^{-6}`.  If I decrease it to `10^{-12}`, I get this plot:


So, something is going wrong with `r=0.01` near `b=0` and `b=1-r` (and less so near `b=1+r`);  I'll track this down and see what is the causing the derivative problem (probably another near-cancellation of large numbers).   The `r>1` case still has errors near `r=b`, which may be a similar problem as the `s_2` case.

![sn_derivative_error_epsilon1em12](https://user-images.githubusercontent.com/243664/41811786-2f9880f4-76cb-11e8-8741-35b415e448ec.png)


And my Julia code crashes when I get too close to `b=r-1` for `r=100` (it crashed when `b-r+1 = 10^{-15}`).

**Comment by ericagol** [comment]
The derivative of `I_v` is particularly simple:

![image](https://user-images.githubusercontent.com/243664/41812756-aba97cfe-76dd-11e8-8835-9be33ef62caf.jpeg)

`\frac{\partial \mathcal{I}_v}{\partial b} & = \frac{1}{2}k^{2v} \frac{\partial \kappa}{\partial b}\\
\frac{\partial \mathcal{I}_v}{\partial r} & = \frac{1}{2}k^{2v} \frac{\partial \kappa}{\partial r}`

However, `J_v` is much more complicated...

**Comment by rodluger** [comment]
Hmmm. I'm not sure that makes sense. How could the error on our derivatives
be smaller when compared to an inaccurate (epsilon = 1e-6) estimate versus
an accurate (epsilon = 1e-12) one?

**Comment by ericagol** [comment]
Sorry - the epsilon parameter measures how close to b=1-r that I am computing the model.  So, as b approaches 1-r, the error grows.

I actually think that if we go back to computing I_uv with the same approach as H_uv that we are using now, this may fix the problem.

**Comment by ericagol** [comment]
There also may just be a problem with how I coded this up - perhaps your version won't show this growth of error on the derivative in the `b=1-r` limit?

**Comment by rodluger** [comment]
Ah, I see. I will try to code it up this weekend. Did you figure out the
Lambda derivatives in terms of cel?

**Comment by ericagol** [comment]
Yes - I just used the expression from Bulirsch (1969) to convert `\lambda K(k) + \mu E(k)` to cel.

**Comment by rodluger** [comment]
Can you TeX them up for the record when you get a chance?

**Comment by rodluger** [comment]
@ericagol 
I get the same increase in the error of the derivative in the limit `b --> 1 - r`. I also get the same behavior as you when `b --> 0` and `b --> 1 + r`:
![image](https://user-images.githubusercontent.com/9323819/41824637-5d5bed3e-77c8-11e8-9083-a4967af13120.png)
These are the errors on the actual *flux*, though, but since I'm not performing any rotations it amounts to the same thing. Also, these are the derivatives with respect to `b` -- I'm assuming that's what you plotted?

**Comment by rodluger** [comment]
Here are my derivatives with respect to `r`. They are quite similar.
![image](https://user-images.githubusercontent.com/9323819/41824681-5ad6376c-77c9-11e8-893f-5918a7c406fe.png)

**Comment by rodluger** [comment]
@ericagol Oh, never mind. My `r = 100` derivatives are fine. They look bad here because I'm computing the numerical derivatives in python, *after* casting my `bigdouble` fluxes to `double` so that I can pass them to `numpy`. If I decrease my step size for the numerical derivative, I get better results; but I can only decrease it so far before I start getting numerical error on the numerical estimate of the derivative!

The noise floor of 1 ppm - 1 ppb in the `r = 0.01` plots is also inflated because of this. In practice I think my derivs are close to machine precision, just like yours.

I could calculate these the correct way but it would take a bit of re-coding on the C++ side...

**Comment by ericagol** [comment]
@rodluger But the spike that both of us find at `b=1-r` for `r=0.01` is likely due to the auto diff numerical errors, right?

**Comment by rodluger** [comment]
@ericagol The spike at `b=1-r` is in fact an autodiff instability. If I plot the derivative in the vicinity of that point I see wild oscillations. Another way to confirm this is to plot the difference between `ds(b)/db` and `0.5 * (ds(b-eps)/db + ds(b+eps)/db)` where `eps` is machine epsilon. This is a direct test for instability: at the smallest scales, the function should be linear, so these expressions should be nearly identical. This also circumvents any issues with numerical instability in the `BigFloat` calculation. Here's what I get with this definition:
![image](https://user-images.githubusercontent.com/9323819/41860768-4d27cb36-7854-11e8-9f89-ac636ba66ba4.png)
Looks like the instability at `b=0` is also real.

**Comment by rodluger** [comment]
@ericagol It's easy to imagine why autodiff is unstable in certain places. We've reparametrized our equations to eliminate expressions involving the differences of two nearly identical numbers. But this does not guarantee the stability of the *derivatives*, since the derivatives of terms in our expressions might experience near-cancellation.

@dfm Do you have any insights into this? I found nothing online about numerical stability of autodiff: everyone seems to claim it's numerically stable...

**Comment by dfm** [comment]
I'm not sure that I'm totally following all the discussion... there could absolutely be over/under flow errors introduced by the gradient propagation, but I'm lost enough here that I don't know what is specifically happening here.

**Comment by rodluger** [comment]
I don't think the details matter too much. The big picture is that we reparametrized our equations for the flux so that they are *very* numerically stable at all values of the impact parameter `b` and the occultor radius `r`. But we're finding that in certain limits, the derivatives of these expressions computed by autodiff blow up. And yes, it's typically because of underflow: in some limits, we must be taking the difference between two derivatives that are almost but not exactly the same, which leads to numerical instabilities down the line. My questions was more of a general /theoretical one: is there a standard way of dealing with this? Could reverse mode AD help? Have people looked into these stability issues that you know of?

**Comment by dfm** [comment]
I'm not aware of any research into this and it's not obvious to me that reverse mode autodiff would help. At a fundamental level, autodiff is just applying the chain rule so you might have to try to audit where you're getting two gradients with similar signs and try to reparameterize there as you've been doing for the value. Another thing to consider would be providing your own analytic gradients for some component of the model where the error is being introduced.

**Comment by rodluger** [comment]
Gotcha. Yes, @ericagol is going to town on computing the derivatives by hand. @ericagol if this proves too difficult, I'm not above adding a hack to fix this. The region of parameter space where our expressions are unstable is quite small, so we could just take the performance hit and compute the derivatives using `BigFloat` in that vicinity...

**Comment by ericagol** [comment]
@rodluger Okay, I have a partial fix.  Computing `I_0 = 2\cos^{-1} k_c` when `k^2 > 1/2` seems to fix the cases with the largest errors near `b=1-r` when `r=0.01`.

![sn_derivative_error_r0 01](https://user-images.githubusercontent.com/243664/41879790-fd08882a-788f-11e8-8fca-ca8338c4cbd9.png)

However, even though the derivative agrees, I'm getting some oddly shaped fluxes very close to `b=1-r`, and this also doesn't fix the problem near `b=0`.

**Comment by ericagol** [comment]
Here's a TeXed version of the `s_2` expressions:

![image](https://user-images.githubusercontent.com/243664/41887843-5835bf8e-78b7-11e8-8791-a7215acc0ef1.jpeg)

`\frac{\partial \Lambda}{\partial r} &= \frac{8br^2 E(k^2) + 2r(1-(b+r)^2)K(k^2)}{\pi\sqrt{br}}\\
&= \frac{1}{\pi\sqrt{br}}\mathrm{cel}(k_c,1,2r(1-(b-r)^2),0)\\
 \frac{\partial \Lambda}{\partial b} &= \frac{4r(r^2+b^2-1) E(k^2) + 2r(1-(b+r)^2)K(k^2)}{3\pi\sqrt{br}}\\
&= \frac{1-(b-r)^2}{3\pi \sqrt{br}} \mathrm{cel}(k_c,1,-2r,(1-(b+r)^2)/b)\\
 \frac{\partial \Lambda}{\partial r} &= \frac{4r}{\pi}\sqrt{1-(b-r)^2} E(k^{-2})\\
&= \frac{4r}{\pi}\sqrt{1-(b-r)^2} \mathrm{cel}(k_c,1,1,k_c^2)\\
 \frac{\partial \Lambda}{\partial b} &= \frac{2}{3b\pi}\sqrt{1-(b-r)^2}\left[(r^2+b^2-1) E(k^{-2}) +(1-(b+r)^2)K(k^{-2})\right]\\
&= \frac{4r}{3\pi}\sqrt{1-(b-r)^2}\mathrm{cel}(k_c,1,-1,k_c^2)`

**Comment by ericagol** [comment]
Maybe the hack is the way to go...  I'm not making much headway on improving the accuracy, and I'm not sure that I'm up for computing all of the derivatives by hand, coding them up, and testing.

**Comment by rodluger** [comment]
The hack it is then. Thanks for pushing through this far! Sounds like we
mostly just need a hack for b~0? And what's the second highest peak in your
last plot?

**Comment by ericagol** [comment]
The second-highest peak is near `b=1-r`.

**Comment by ericagol** [comment]
I did improve the `b ~ 0` for `r=0.01` a bit by computing `J_0` and `J_1` in the `k^2 >> 1` case in which we iterate downwards from large `J_v`.   Now the maximum error on the derivatives is `<10^{-3}` for `b=10^{-12}`.  However, this is likely to grow for smaller `b`, so the hack is still going to be necessary.

**Comment by ericagol** [comment]
And, if we get very close to `b=1-r` (say, `10^{-15}`), then the errors grow to order unity again.

Another option might be to just revert to the `b=1-r` case when `b` is close enough to `1-r`.

**Comment by rodluger** [comment]
Cool. I'm happy to just hack our problems away in these limits.

**Comment by ericagol** [comment]
@rodluger Which `\mu,\nu` values are those?

Here is my latest.  I found that computing `I_0 = \cos^{-1}(k_c)` fixed the region just above `b=1-r`.

![sn_derivative_error_lmax_5_r0 01](https://user-images.githubusercontent.com/243664/41953774-686a3288-798c-11e8-9ffd-55ccf670d106.png)

**Comment by rodluger** [comment]
Oops, my bad. I had `s1` and `s3` mixed in. Here's the plot just for s2, and it looks great.
![image](https://user-images.githubusercontent.com/9323819/41983372-bf2f03ea-79e2-11e8-85b4-13b936cb2e9d.png)
However, I am finding that `cel` does not converge in the `r = 100` case within `1e-12` of `r - 1` and `r + 1`...

**Comment by ericagol** [comment]
@rodluger Is that problem occurring for `s_2`, or for the others?

Unfortunately with my latest changes, the errors on the `r=100` case have gotten larger...

![sn_derivative_error_lmax_5_r100](https://user-images.githubusercontent.com/243664/41984636-f9895236-79e5-11e8-850f-fe969cffc74e.png)

But, `s_2` seems fine within `10^{-12}` of `r-1` (and same with the other terms).

**Comment by ericagol** [comment]
(I haven't made color scheme consistent yet).

**Comment by rodluger** [comment]
@ericagol I figured it out. `cel` didn't converge specifically when evaluating `s_2` near `b = r - 1` and `b = r + 1`. In these limits `k^2` is very close to zero and `kc^2` is very close to one, and whatever expression I was using for `kc` was not very precise. Taking `kc^2 = 1 - k^2` fixed the issue.

**Comment by ericagol** [comment]
@rodluger  I think I mentioned this before, but I found that it is better to evaluate `k_c` directly in terms of `b` and `r`.  The `cel` algorithm doesn't make use of `k^2` (except when `p=0`, which is rare), so I found that it is better to just use `k_c` in the cel algorithm.

**Comment by rodluger** [comment]
Actually that's what I had been doing. But the problem is that when `b --> 1 - r`, this expression
```
kc^2 = -(1 - (b + r) ^ 2) / (4 * b * r)
```
evaluates to a number that's very close to one. I find it to be more stable to compute
```
kc^2 = 1 - k^2
```
in this limit, since `k^2` is close to zero and more precise.

**Comment by ericagol** [comment]
Okay, that's great!  So, now I have four cases for evaluating `k_c` (in addition to the special cases):

```
  k2 = (1.0-(b-r)^2)/(4b*r);
  if k2 > 1
    if k2 > 2.0
      kc = sqrt(1.-inv(k2))
    else
      kc = sqrt(abs(((b+r)^2-1)/((b-r)^2-1)))
    end
  else
    if k2 > 0.5
      kc = sqrt(abs(((b+r)^2-1))/(4*b*r))
    else
      kc = sqrt(1.-k2)
    end
  end
```

**Comment by rodluger** [comment]
Things look good on my end too. I am now computing the numerical derivatives in C++ using `bigdouble`, so this is the most accurate plot I have so far.
![image](https://user-images.githubusercontent.com/9323819/41991358-fbbcd244-79f9-11e8-9028-5693df1f038e.png)

**Comment by ericagol** [comment]
@rodluger  You are doing better than I am for `r=100`;  I wonder what the difference is?

![sn_derivative_error_lmax_5_r100](https://user-images.githubusercontent.com/243664/41991722-5a8dd54c-79fb-11e8-9cf6-c0286a03905d.png)

**Comment by rodluger** [comment]
@ericagol Strange. I think there are small differences in how we compute lambda, phi, and k^2 (for instance). But I'm not too worried -- both look great.

I'm having a bit of trouble overriding the autodiff derivatives with `bigdouble` numerical derivatives. Would it be hard to derive a first order approximation to ds/db (or dP/db) when b = 0? Something that works below 1e-12. I imagine even a *zeroth* order approximation would work well.

**Comment by ericagol** [comment]
@rodluger Looking at equation (D25), if `b+r <1`, then `\phi` is constant, so the derivative
is equal to `dP/db = (\nu/2) 2(2r)^{l+2} K_{\mu/4+1,\nu/2-1}`, I think.  If so, this may work in the general case as well, but not during ingress/egress.

For the odd case, I find at `b=0` that

![image](https://user-images.githubusercontent.com/243664/42005132-d582bf48-7a27-11e8-9f31-54e4fa9c1290.jpeg)

`\frac{\partial P}{\partial b} &= \frac{\nu-1}{2} (1-r^2)^{3/2} \int (r c_\varphi)^{\tfrac{\mu-1}{2}} (r s_\varphi)^{\tfrac{\nu}{2}-\tfrac{3}{2}} d\varphi\\
&+ \frac{3}{2} (1-r^2)^{1/2} \int (rc_\varphi)^{\tfrac{\mu-1}{2}} (r s_\varphi)^{\tfrac{\nu}{2}+\tfrac{1}{2}} d\varphi`

which we should be able to express in terms of the other functions we have defined (note that these integrals are `I_{uv}` in terms of your first notation).

**Comment by ericagol** [comment]
Assuming I haven't made a mistake, the recursion relation for `H_{uv}` with `\lambda = \pi/2` may be used to simplify this:

![image](https://user-images.githubusercontent.com/243664/42005536-d7a11048-7a29-11e8-9e75-1cc2d4f030b6.jpeg)

`\frac{\partial P}{\partial b} &= \frac{\nu-1}{2} (1-r^2)^{3/2} \int (r c_\varphi)^{\tfrac{\mu-1}{2}} (r s_\varphi)^{\tfrac{\nu}{2}-\tfrac{3}{2}} d\varphi\\
&+ \frac{3}{2} (1-r^2)^{1/2} \int (rc_\varphi)^{\tfrac{\mu-1}{2}} (r s_\varphi)^{\tfrac{\nu}{2}+\tfrac{1}{2}} d\varphi\\
&= \frac{\nu-1}{2} (1-r^2)^{1/2} r^{l-2} \left[1+r^2(\frac{3}{2l}-1)\right] H_{(\mu-1)/2,\nu/2-3/2}`

**Comment by rodluger** [comment]
@ericagol 
I'm finally getting back to this and I'm a bit lost among all the proposed solutions to tackling derivative stability. From some tests I've been running, `starry` is unstable near `b = 0` and `b = 1 - r` and things go a little haywire everywhere when `r = 0.5`. Can you point me to the things you've implemented on your end to address these issues? Did you verify the two equations above are correct? Thanks!

**Comment by ericagol** [comment]
@rodluger I haven't checked the above equations yet.  I'm thinking that the approach I used to stabilize the limb-darkening computations in `transit_poly.jl` may help with computing `s_n` as well, but I haven't tried this out yet.

**Comment by ericagol** [comment]
@rodluger One thing that I found helped with the `b~0` case was to compute `J_0` and `J_1` for `k^2 >>1` from the elliptic integral formulae rather than by recursion.  See this commit:

https://github.com/rodluger/starry/commit/5409919599a01ddc7fb4bff1d34a44f910071f1e

But, I ended up commenting out the `k^2<1` part.

**Comment by rodluger** [comment]
@ericagol Doing what you said above seems to make the instability /worse/ for me. I'm going to dig into this more on my flight back tonight.

**Comment by ericagol** [comment]
Interesting.  I'll try to look into it as well;   I've been pushing to write up what I've done for the limb dark paper (since you were hoping to submit that nearly concurrently with STARRY), but I can get back to this as well.

**Comment by rodluger** [comment]
Cool, thanks. Don't sweat it too much with limbdark; I haven't had any time
lately to work on it, so I was thinking of submitting starry now and maybe
trying to sync when the two papers actually show up on the arxiv in a
couple months.

**Comment by ericagol** [comment]
Well, part of the reason I'm trying to finish is that I have other projects to move onto, and I'd like to get this wrapped up as well!

**Comment by rodluger** [comment]
Works for me then! I'll try to start coding up all that stuff into `starry`
in the next few days.

**Comment by rodluger** [comment]
I'm upgrading this issue from `bug` to `enhancement`. The derivatives are no longer `NaN` anywhere and remain stable within `1e-9` of the unstable points. Closer in than that, the errors approach unity, but in practice this should never be encountered. I've added code to ensure that *at* the actual limits, the derivatives are correct.

**Comment by rodluger** [comment]
Migrated to #186.
