### ISSUE TITLE
Compute gradients of the map coefficients manually for speed

### ISSUE THREAD

**Issue by rodluger** [rodluger/starry#124]
Resurrecting the comment from #119 :

I think the derivatives of the flux with respect to the map coefficients are rather trivial, since our model is linear in the Ylms. Currently, gradient evaluations are rather slow because the derivative vectors I'm passing around to all functions are long and mostly full of zeros. If we compute the gradients w.r.t. the map coefficients manually, we can greatly reduce the size of the derivative vector and speed things up.

**Comment by dfm** [comment]
This is absolutely a good idea!!

**Comment by rodluger** [comment]
This seems to be working great. Will commit changes soon.

**Comment by rodluger** [comment]
This has now been implemented!
