### ISSUE TITLE
selective override of Eigen autodiff?

### ISSUE THREAD

**Issue by rodluger** [rodluger/starry#125]
@dfm When I'm computing (say) an elliptic integral, I manually define its gradient like this:
```C++
  // Gradient of K
  template <typename T>
  Eigen::AutoDiffScalar<T> K (const Eigen::AutoDiffScalar<T>& z)
  {
    typename T::Scalar ksq = z.value(),
                       Kz = K(ksq),
                       Ez = E(ksq);
    return Eigen::AutoDiffScalar<T>(
      Kz,
      z.derivatives() * (Ez / (1.0 - ksq) - Kz) / (2 * ksq)
    );
  }
```
How can I do this selectively, i.e., choose whether or not to use this analytic expression depending on the value of `z`? Is there a way to place an `if` statement in there that tells `Eigen` to go ahead and autodiff it in some cases?

**Comment by rodluger** [comment]
Also in this vein, is there a way to provide the derivatives w.r.t. one of the input parameters, and have Eigen compute the other one?

**Comment by dfm** [comment]
For conditional autodiff, I think that you'd probably implement it as something like this (disclaimer: typed in the browser):

```c++
template <typename T>
T evaluate_K (const T& z) {
     // compute K with type T...
}

double K (const double& z) {
     return compute_K<double>(z);
}

template <typename T>
Eigen::AutoDiffScalar<T> K (const Eigen::AutoDiffScalar<T>& z) {
    if (z < whatever) {
        return analytic_gradient;
    }
    return compute_K<Eigen::AutoDiffScalar<T> > (z);
}
```

I can't think of a way to only compute the gradient wrt to just one parameter, so tell me more about the use case and I'll brainstorm.

**Comment by rodluger** [comment]
@dfm Nice, thanks.
The derivative of the flux is unstable with respect to the impact parameter in some cases, but not with respect to the radius or the map coefficients. I was hoping to have Eigen compute the latter and provide an explicit formula for the former.

**Comment by dfm** [comment]
OK - you might be able to do something like (the usual disclaimer...):

```c++
template <typename T1, typename T2>
T1 compute_func (const T1& a, const T2& b) {
    // compute the function value as usual
}

double func (const double& a, const double& b) {
    return compute_func(a, b);
}

template <typename T>
Eigen::AutoDiffScalar<T> func (const Eigen::AutoDiffScalar<T>& a, const Eigen::AutoDiffScalar<T>& b) {
    Eigen::AutoDiffScalar<T> b_var = b;
    b_var.derivatives().setZero();
    Eigen::AutoDiffScalar<T> result = compute_func(a, b_var);
    result.derivatives() += b.derivatives() * analytic_grad_wrt_b;
    return result;
}
```

**Comment by rodluger** [comment]
Nice, thanks! Will try this out.

**Comment by rodluger** [comment]
@dfm Now that I've thought about this some more, I think it's going to be a huge pain to re-template the code to accommodate this. I was thinking an easier workaround is to do
```C++
template <typename T>
Eigen::AutoDiffScalar<T> func (const Eigen::AutoDiffScalar<T>& a, const Eigen::AutoDiffScalar<T>& b) {
    Eigen::Vector<T> b_derivatives = b.derivatives();
    b.derivatives() = Eigen::Vector<T>::Zero(b.derivatives().size);
    Eigen::AutoDiffScalar<T> result = compute_func(a, b);
    result.derivatives() += b_derivatives * analytic_grad_wrt_b;
    return result;
}
```
I.e., we cache the actual derivative vector of `b`, zero it out to compute the function as normal, then add the analytic derivative back in. Does this look OK?
