### ISSUE TITLE
Figure 18 precision

### ISSUE THREAD

**Issue by ericagol** [rodluger/starry#127]
I would expect the precision of Spiderman to improve with the number of layers, but the size of the dots appears to be constant for `n_layers >= 10`.  Is this true, or is there a bug in the code that creates the plot?  Or perhaps it is too difficult to see a linear decrease in the size of the dots which have a logarithmic scaling?

**Comment by dflemin3** [comment]
The Spiderman precision appears to scale linearly with n_layers, so there is an improvement in the precision, but it's pretty small and isn't too apparent on the log scale.
