### ISSUE TITLE
Instabilities in the s2 term

### ISSUE THREAD

**Issue by rodluger** [rodluger/starry#13]
The elliptic integrals K and Pi in the Mandel & Agol solution diverge when k --> 1. The result is still finite, since things cancel, but we should find a way to re-parametrize this.

I think some of the functions for the higher order terms might also diverge when k --> inf, but I need to investigate this further.

**Comment by ericagol** [comment]
Abramowitz & Stegun equation (17.3.26) shows that lim_{k^2->1} (K-1/2*\ln{16/(1-k^2)}) = 0.  

I checked equations (A2), and it looks like in all cases that n^2 < 0.

This corresponds to Case (iv) Circular Case n< 0 in Abramowitz & Stegun, in which case
we can use the relations (17.7.15) & (17.7.17).  Note:  A&S' n is n^2 & sin(\alpha) = k.

With this substitution, the elliptic integrals still diverge _however_ , the pre-factors go to zero as k -> 1!   Since the elliptic integrals only diverge logarithmically, then this should work out fine.

By the way:  there is a typo in equation (A2) that I just found:  in the k^2>= 1 case, the 3 should be a 6.

This makes a significant improvement to the quadratic limb-darkening case, as well as the simplification of the number of cases that you found.  It might be worth writing a short paper on (as well as checking the other cases which have cancellation of divergences).  I've been meaning to look into this for quite a few years:  I'm glad this prompted me to finally do so!

**Comment by rodluger** [comment]
Hi Eric,

Thanks for these relations! I'll work those into the paper and we can chat more about writing a letter on these improvements. 
And thanks for catching the typo. That 2 in front of the K term should be multiplying all three elliptic integrals. I had it right in my code, which is why I didn't catch it!

**Comment by ericagol** [comment]
Yep, that's how I missed the typos in M&A...   I'm working through the full transformations of the equations - I think they will be more elegant.

**Comment by ericagol** [comment]
We should compare with Pal's solution, which also includes the derivatives:

**Comment by rodluger** [comment]
Copying email exchange with Eric for future reference:

@rodluger wrote:

> I implemented your re-parametrized version of Mandel & Agol and verified that it works. However, there are still numerical issues when evaluating the linear limb darkening term in the vicinity of b = r. Attached is a plot of the flux of the Y_{1,0} spherical harmonic being occulted by a planet with r = 0.4 as it crosses through b = 0.4. 
> 
> The issue, as you mentioned earlier, is that the Pi elliptic integral diverges in this limit. We're multiplying it by (b - r), which in principle should keep the result finite, but in practice we get bad numerical instabilities.
> 
> Any suggestions on how to tackle this? I tried Taylor expanding the integrand of the elliptic integral about b = r, but couldn't get that to work -- not sure why.

@ericagol wrote:

> Equation (17.7.14) in Abramowitz & Stegun expresses this in terms
> of incomplete elliptic integrals of the first and second kinds. This
> seems to do the trick - the attached code & plot computes just
> the \Pi(n,k) terms in your \Lambda function.
> 
> You can see that the transformed expression is much more
> numerically stable.
> 
> PS - I compute the incomplete elliptic integrals of the first and second
> kinds with the Julia package "Elliptic".  It might be good to not have
> this dependency, but the Bulirsch expressions for these incomplete
> elliptic integrals are a function of x = tan(\phi), which blows up as
> \phi -> \pi/2!
> 
> PPSS - It might be worth examining other edge cases of Mandel &
> Agol to see whether there are additional numerical instabilities which
> can be tamed.

![image](https://user-images.githubusercontent.com/9323819/37675922-bd8d9918-2c33-11e8-8d5a-17402e59db7f.png)

![elliptic_pi_transformation](https://user-images.githubusercontent.com/9323819/37675920-bd6a6f2e-2c33-11e8-9bf2-44002c3e8016.png)

[test_ellpi.txt](https://github.com/rodluger/starry/files/1830705/test_ellpi.txt)

**Comment by rodluger** [comment]
@ericagol , if you think this is the best approach, I will code up the [Julia incomplete elliptic integral routine](https://github.com/nolta/Elliptic.jl/blob/master/src/slatec.jl#L244) in C++ and use that to compute the PI term in the vicinity of b = r.

BTW, I think another region of numerical instability is near abs(b - r) = 1. This is close to first and last contact, where you can see from Figure 7 in the paper that my errors grow quickly. I think this is due to the denominator [in this expression](https://github.com/rodluger/starry/blob/master/starry/lib/starry/solver.h#L306).

**Comment by ericagol** [comment]
It looks like these may be the Carlson elliptic integrals, which are discussed and implemented in Numerical Recipes.

**Comment by ericagol** [comment]
@rodluger  When I have time, I would like to go through the equations in all of the limits where divergences might occur, and see whether there are transformed expressions which can avoid divergences.

**Comment by rodluger** [comment]
Resolved!
