### ISSUE TITLE
Switch to templated Eigen types instead of homebuilt matrices

### ISSUE THREAD

**Issue by dfm** [rodluger/starry#15]
This will be easier to maintain and get higher performance. I'll see what I can do to take a stab at this over the weekend.

**Comment by rodluger** [comment]
Cool. The one matrix inversion I do -- to compute the change of basis matrix -- is a one-time thing, so optimizing that is not essential. Also, it's a super sparse matrix of integers with block structure, so I'm sure we could find a way to invert it without a brute force inversion routine.

But I do take a few dots products of matrices and vectors every iteration. Can Eigen really speed those up? I would imagine there's only one way to do it!

**Comment by dfm** [comment]
I meant everything in here: https://github.com/rodluger/starry/blob/master/starry/cpp/integrate.cpp

You shouldn't ever allocate arrays of arrays to create matrices!!

And yes - you can get much faster dot products because most CPUs include vectorized operations for these types of things.

**Comment by rodluger** [comment]
Ah, sweet. Knock yourself out then :) If you have a chance, I commit
similar sins in the rotation module
<https://github.com/rodluger/starry/blob/master/starry/cpp/rotate.cpp>.
Note that I had to mess around with the pointers to create a matrix that is
indexed from -m to m (instead of 0 to 2m).

**Comment by rodluger** [comment]
Done!
