### ISSUE TITLE
Default values for "r" and "L"

### ISSUE THREAD

**Issue by dfm** [rodluger/starry#172]
These should be documented here: https://rodluger.github.io/starry/api.html#starry.kepler.Secondary.r but I can't figure out your docstring magic to make that work. For a secondary, the default `r` seems to be `0.1` and the default `L` is `0.0`, I think.

**Comment by rodluger** [comment]
@dfm Thanks for pointing this out. Yes, those are the defaults. I've pushed changes that should propagate to the docs once the tests run on travis.

**Comment by dfm** [comment]
excellent.
