### ISSUE TITLE
Fix Linux builds

### ISSUE THREAD

**Issue by rodluger** [rodluger/starry#180]
Currently the code appears to be a factor of ~3-5 slower on Linux than on Mac, and the executable sizes are 1-2 orders of magnitude (!!!) larger. Look into this.

**Comment by rodluger** [comment]
@dfm I think I figured it out. `setuptools` passes the `-g` flag to the compiler by default, which adds a ton of debug information to the build. On Mac that doesn't amount to much (or perhaps `clang` ignores the request), but on Linux it *really* matters. I got my executable from 725MB down to 6.8MB (!!!) The build still takes forever, and I haven't done speed tests to see if the code runs faster, but I think this is a win!

**Comment by dfm** [comment]
Crazy! Good find.

On Wed, Nov 7, 2018 at 3:35 PM Rodrigo Luger <notifications@github.com>
wrote:

> @dfm
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_dfm&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=AvKCBU-zyph1qdf6NaatMQ&m=Ep_M_RP-F6Vs34itgAn-mzRkIllVL24nU5A61-fyqOQ&s=a2ze16r79ANahiLxzvTbYj0235AXu9aPJyYsbyKgfS8&e=>
> I think I figured it out. setuptools passes the -g flag to the compiler
> by default, which adds a ton of debug information to the build. On Mac that
> doesn't amount to much (or perhaps clang ignores the request), but on
> Linux it *really* matters. I got my executable from 725MB down to 6.8MB
> (!!!) The build still takes forever, and I haven't done speed tests to see
> if the code runs faster, but I think this is a win!
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_rodluger_starry_issues_180-23issuecomment-2D436768051&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=AvKCBU-zyph1qdf6NaatMQ&m=Ep_M_RP-F6Vs34itgAn-mzRkIllVL24nU5A61-fyqOQ&s=QlrUNrv_GYf8E9XTRo4VktmiRnPeZm_W3Bi5nZUe10c&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AAVYStSV4Z5BnWGYjU0OocwnETz4kJIQks5us0QTgaJpZM4YQjcB&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=AvKCBU-zyph1qdf6NaatMQ&m=Ep_M_RP-F6Vs34itgAn-mzRkIllVL24nU5A61-fyqOQ&s=64_FYmx6ZTT9bm4RipswA1BEvsEaVeD2e43G9NMVJ38&e=>
> .
>
-- 
Dan Foreman-Mackey
Associate Research Scientist
Flatiron Institute
http://dfm.io
