### ISSUE TITLE
Eclipse depth vs Phase Curve Ampitude

### ISSUE THREAD

**Issue by exowanderer** [rodluger/starry#187]
**Motivation**
I am trying to use the `system.lightcurve` in `starry` with my `emcee` implementation to fit a `starry` phase curve model to my Spitzer photometry.

**Background**
When I ran a MCMC analysis on existing Spitzer+Phase Curve code ([skywalker](https://github.com/munozcar/SKYWALKER)), I found that the eclipse depth with `STARRY` was roughly twice the eclipse depth measured using _only_ a cosine function for the phase curve; i.e: 

```python
ang_freq = 2*pi/period
phase_curve = half*cosAmp*np.cos(ang_freq * (times - (t_secondary - cosPhase)))
```
[Sidenote: The `half` in my formula is critical because the "amplitude" I want to measure is the 
`top - bottom` of the flux *at* the eclipse location. The result is that the measurement of "cosAmp" is the `top - bottom` of the phase curve; and the cosPhase provides the adjustment to "at the eclipse location"]

**Issue**
I want to use `STARRY` to interpret the eclipse depth, phase curve amplitude, phase curve offset, night flux, and orbital parameters (e.g. eccentricity, a/Rs, etc) from the MCMC fit of the phase curve. 

The figure below shows three different phase curves: 
1. (blue) with no eclipse and no phase curve amplitude
2. (orange) with an eclipse (FpFs=1000ppm) and no phase curve amplitude
3. (green) with an eclipse (FpFs=1000ppm) and phase curve amplitude set to 1.0 (Y_1_0 = 1.0). 

![zoomed_phase_curve_compare_eclipse_vs_sph_harmonics](https://user-images.githubusercontent.com/11221046/52685896-711e2680-2f19-11e9-9bdb-26e94d1c8819.png)

In this figure, an observer would say that that the
1. "eclipse depth of the blue curve is 0.0"
2. "eclipse depth of the orange curve is 1000ppm"
3. "eclipse depth of the green curve is 2200ppm"

Unfortunately, the input that I used for the eclipse depth to both the orange & green curves was identical (FpFs = 1000ppm). 

I would expect -- because the phase curve offset is zero -- that the difference between the top and bottom of the green curve should be identical to the difference between the top and bottom of the orange curve. 

The "eclipse depth" is the loss of flux during eclipse; but (*I think*) the MCMC enters the eclipse depth as a free parameter (`planet.L` below) and the phase curve amplitude (`planet[1,0]` below) as an independent free parameter. 

In the end, the MCMC shows that `planet[1,0]` and `planet.L` are strongly correlated (Pearson > 0.9), which is intuitive; but for zero phase curve offset and no night flux, the eclipse depth should *equal* the day-to-night variation; here the day-to-night side variation is greater than *twice* the *entered* eclipse depth.

To an observer, if I provide a model with the `fpfs` (see below) and `cosAmp` (half day-to-night variation) -- at no phase curve offset and no night flux -- I would expect the *orange* curve to reach maximum at the top of the eclipse and reach minimum at the top of the transit. The green `starry` curve has a maximum >2x larger the than maximum for the orange curve; and a minimum **below** the bottom of the orange/green eclipse.

I think that the issue is, as an observer, I want to interpret `planet[1,0]` as the day-to-night variation (~phase curve amplitude) and `planet.L` as the eclipse depth (~Fp/Fs).

**[tl;dr]: Could you guide me on how to infer the physical parameters (eclipse depth & phase curve amplitude) from the STARRY light curve results?**

[Related side note: The flux at the top of the transit should **never** be less than the flux at the bottom of the eclipse; see green curve < blue curve at transit.]

----
Here is a code snippet to reproduce this figure:

```python
from starry import kepler

from pylab import *; ion()
import numpy as np
import exomast_api # pip install git+https://github.com/exowanderer/exoMAST_API
planet_info = exomast_api.exoMAST_API(planet_name='HD 189733 b')

lmax  = 1

''' Instantiate Kepler STARRY model; taken from HD 189733b example'''
# Star
star = kepler.Primary()

# Planet
lambda0 = 90.0

planet = kepler.Secondary(lmax=lmax)
planet.lambda0 = lambda0 # Mean longitude in degrees at reference time
planet.r = planet_info.Rp_Rs # planetary radius in stellar radius
planet.L = 0.0 # flux from planet relative to star
planet.inc = planet_info.inclination # orbital inclination 
planet.a = planet_info.a_Rs # orbital distance in stellar radius
planet.prot = planet_info.orbital_period # synchronous rotation
planet.porb = planet_info.orbital_period # synchronous rotation
planet.tref = planet_info.transit_time # MJD for transit center time

planet.ecc = planet_info.eccentricity # eccentricity of orbit
planet.Omega = planet_info.omega # argument of the ascending node

planet[1,0] = 0.0 # Y_1_0

# System
system = kepler.System(star, planet)
# Instantiate the system
system = kepler.System(star, planet)

# Specific plottings
fpfs = 1000/1e6
Y_1_0 = 1.0

phase = np.linspace(-0.5, 0.5, 1000)
times = phase*planet_info.orbital_period + planet_info.transit_time

fig = gcf()
ax = fig.add_subplot(111)
system.compute(times)
ax.plot(times,system.lightcurve)

planet.L = fpfs
system.compute(times)
ax.plot(times,system.lightcurve)

planet[1,0] = Y_1_0
system.compute(times)
ax.plot(times,system.lightcurve)
ax.set_ylim(1-fpfs,1 + 2.5*fpfs)

ax.set_xlabel('Time [day]', fontsize=30)
ax.set_ylabel('normalized flux', fontsize=30)

ax.set_title('STARRY:Compare Influence of FpFs vs CosAmp', fontsize=30)

ax.legend(('FpFs=0ppm      ; Y_1_0=0.0', 
                     'FpFs=1000ppm; Y_1_0=0.0', 
                     'FpFs=1000ppm; Y_1_0=1.0'),loc=0, fontsize=20)

for tick in ax.xaxis.get_major_ticks():
    tick.label.set_fontsize(20)
for tick in ax.yaxis.get_major_ticks():
    tick.label.set_fontsize(20)
```

**Comment by rodluger** [comment]
@exowanderer Thanks for the **awesome** issue description. I'll play around with things a bit this morning, and we can chat throughout the day, but right off the bat I think the issue is with your interpretation of the `Y_{1,0}` harmonic. That harmonic is symmetric about the plane of the sky, so whatever flux you are adding to the dayside, you are also *subtracting* it from the night side. So by setting `Y_{1,0} = 1.0`, you are effectively giving the planet *negative* flux on the night side, which explains why the phase curve dips below 1 near transit.

Also, all `Primary` and `Secondary` map instances have the constant `Y_{0,0}` term fixed at unity (which is something I'm considering changing & we can chat about), so by also setting the `Y_{1,0}` coefficient to unity, you are effectively doubling the brightness of the dayside. That's why the eclipse depth of your green curve is about twice that of the orange curve. If you want them to be the same, you should probably adjust the *luminosity* of the body. So you could probably get what you want -- matching eclipse depths -- by decreasing the overall luminosity of the planet when plotting the green curve. We can probably sit down and figure out the math behind all this so you don't have to eyeball it.

> I think that the issue is, as an observer, I want to interpret `planet[1,0]` as the day-to-night variation (~phase curve amplitude) and `planet.L` as the eclipse depth (~Fp/Fs).

Ah, yes, that's exactly the issue! `planet.L` is the 4-pi steradian integrated intensity (i.e., the actual luminosity), which is *different* from the eclipse depth. And `planet[1,0]` is the strength of the dipole term, which is *proportional* to the phase curve amplitude. Let's sit down today and chat more about our definitions and try to find a bridge between our conventions.

**Comment by rodluger** [comment]
Oh, and the other thing I'll mention (since this is somewhat buried in our paper). If you just have a dipole map, the way to enforce positivity everywhere on the surface is to make sure that

```python
planet[1, -1] ** 2 + planet[1, 0] ** 2 + planet[1, 1] ** 2 < 1. / 3.
```

In your case, `planet[1,0] = 1`, so the map intensity dips below zero on the night side.

**Comment by rodluger** [comment]
I think this is what you want. Give it a shot, and let's chat more today:
```python
from starry import kepler, Map

from pylab import *; ion()
import numpy as np
import exomast_api # pip install git+https://github.com/exowanderer/exoMAST_API
planet_info = exomast_api.exoMAST_API(planet_name='HD 189733 b')

lmax  = 1

''' Instantiate Kepler STARRY model; taken from HD 189733b example'''
# Star
star = kepler.Primary()

# Planet
lambda0 = 90.0

planet = kepler.Secondary(lmax=lmax)
planet.lambda0 = lambda0 # Mean longitude in degrees at reference time
planet.r = planet_info.Rp_Rs # planetary radius in stellar radius
planet.L = 0.0 # flux from planet relative to star
planet.inc = planet_info.inclination # orbital inclination 
planet.a = planet_info.a_Rs # orbital distance in stellar radius
planet.prot = planet_info.orbital_period # synchronous rotation
planet.porb = planet_info.orbital_period # synchronous rotation
planet.tref = planet_info.transit_time # MJD for transit center time

planet.ecc = planet_info.eccentricity # eccentricity of orbit
planet.Omega = planet_info.omega # argument of the ascending node

planet[1,0] = 0.0 # Y_1_0

# System
system = kepler.System(star, planet)
# Instantiate the system
system = kepler.System(star, planet)

# Specific plottings
fpfs = 1000/1e6

# NOTE: Prevent negative luminosity on the night side
Y_1_0 = 0.5

phase = np.linspace(-0.5, 0.5, 1000)
times = phase*planet_info.orbital_period + planet_info.transit_time

fig = gcf()
ax = fig.add_subplot(111)
system.compute(times)
ax.plot(times,system.lightcurve)

planet.L = fpfs
system.compute(times)
ax.plot(times,system.lightcurve)

# Compute the normalization
map = Map(1)
map[0, 0] = 1
map[1, 0] = Y_1_0
norm = map.flux()

planet.L = fpfs / norm
planet[1,0] = Y_1_0
system.compute(times)
ax.plot(times,system.lightcurve)
ax.set_ylim(1-fpfs,1 + 2.5*fpfs)

ax.set_xlabel('Time [day]', fontsize=30)
ax.set_ylabel('normalized flux', fontsize=30)

ax.set_title('STARRY:Compare Influence of FpFs vs CosAmp', fontsize=30)

ax.legend(('FpFs=0ppm      ; Y_1_0=0.0', 
                     'FpFs=1000ppm; Y_1_0=0.0', 
                     'FpFs=1000ppm; Y_1_0=1.0'),loc=0, fontsize=20)

for tick in ax.xaxis.get_major_ticks():
    tick.label.set_fontsize(20)
for tick in ax.yaxis.get_major_ticks():
    tick.label.set_fontsize(20)
```

**Comment by exowanderer** [comment]
Thanks to our efforts today, I was able to make a conversion script between starry's inputs and phase curve physical properties. There are still some kinks to work out (i.e. the phase curve offset overly modifies the day-to-night contrast); but this is a big step in the right direction:

**No Phase Curve Offset:** Works to the best of my ability to distinguish
![starry_physical_inputs_no_phase_curve_offset](https://user-images.githubusercontent.com/11221046/52769714-16f79100-2fff-11e9-80ff-81223dd47777.png)

**With Phase Curve Offset:** Has issues with anomalous decrease in day-to-night contrast; still best so far!
![starry_physical_inputs_with_phase_curve_offset](https://user-images.githubusercontent.com/11221046/52769748-37275000-2fff-11e9-8273-579ad283c81d.png)


----
# Code snippets to generate plots
```python
def plot_starry_phase_curve_phys(system, planet, times, edepth=0, day2night=0.0, phase_offset=0.0, 
                                 fig=None, ax=None, figsize=(15,10), loc=0, leg_fontsize=15):
    
    if None in [fig, ax]:
        fig = plt.figure(figsize=figsize)
        ax = fig.add_subplot(111)
    
    max_day2night = np.sqrt(3)/2
    Y_1_0 = day2night * max_day2night if edepth > 0 else 0
    
    # cos(x + x0) = Y_1_0*cos(x0) - Y_1n1*sin(x0)
    Y_1_0 = Y_1_0*cos(phase_offset/180*pi)
    Y_1n1 = -Y_1_0*sin(phase_offset/180*pi)
    Y_1p1 = 0.0
    
    map = Map(1)
    map[0, 0] = 1
    map[1, 0] = Y_1_0
    map[1, -1] = Y_1n1
    map[1, 1] = Y_1p1
    norm = map.flux()
    
    planet.L = edepth / norm
    
    planet[1,0] = Y_1_0
    planet[1, -1] = Y_1n1
    planet[1, 1] = Y_1p1
    
    system.compute(times)
    phase = (times - planet.tref) / planet.porb
    ax.plot(phase,system.lightcurve,label='edepth={}ppm; day2night={}; phase_offset={}'.format(edepth, day2night, phase_offset))
    
    # Universal
    if edepth > 0: ax.set_ylim(1-.1*edepth,1 + 1.75*edepth)
    
    ax.set_xlabel('Time [day]', fontsize=30)
    ax.set_ylabel('normalized flux', fontsize=30)
    
    ax.legend(loc=loc, fontsize=leg_fontsize)
    
    for tick in ax.xaxis.get_major_ticks():
        tick.label.set_fontsize(20)
    
    for tick in ax.yaxis.get_major_ticks():
        tick.label.set_fontsize(20)

'''Setup the planet, star, sytem'''
from starry import kepler, Map

from pylab import *; ion()
import numpy as np
try:
    import exomast_api # pip install git+https://github.com/exowanderer/exoMAST_API
except:
    !pip install git+https://github.com/exowanderer/exoMAST_API
    import exomast_api

planet_info = exomast_api.exoMAST_API(planet_name='HD 189733 b')

lmax  = 1

phase = np.linspace(0, 1.0, 1000)
times = phase*planet_info.orbital_period + planet_info.transit_time
''' Instantiate Kepler STARRY model; taken from HD 189733b example'''
# Star
star = kepler.Primary()

# Planet
lambda0 = 90.0

planet = kepler.Secondary(lmax=lmax)
planet.lambda0 = lambda0 # Mean longitude in degrees at reference time
planet.r = planet_info.Rp_Rs # planetary radius in stellar radius
planet.L = 0.0 # flux from planet relative to star
planet.inc = planet_info.inclination # orbital inclination 
planet.a = planet_info.a_Rs # orbital distance in stellar radius
planet.prot = planet_info.orbital_period # synchronous rotation
planet.porb = planet_info.orbital_period # synchronous rotation
planet.tref = planet_info.transit_time # MJD for transit center time

planet.ecc = planet_info.eccentricity # eccentricity of orbit
planet.Omega = planet_info.omega # argument of the ascending node

# Instantiate the system
system = kepler.System(star, planet)

# Eclipse depth
fpfs = 1000/1e6

''' No phase curve offsets'''
fig = plt.figure(figsize=(20,6))
ax = fig.add_subplot(111)

plot_starry_phase_curve_phys(system, planet, times, edepth=0.0 , day2night=0.0, phase_offset=0, fig=fig, ax=ax)
plot_starry_phase_curve_phys(system, planet, times, edepth=fpfs, day2night=0.0, phase_offset=0, fig=fig, ax=ax)
plot_starry_phase_curve_phys(system, planet, times, edepth=fpfs, day2night=0.1, phase_offset=0, fig=fig, ax=ax)
plot_starry_phase_curve_phys(system, planet, times, edepth=fpfs, day2night=0.5, phase_offset=0, fig=fig, ax=ax)
plot_starry_phase_curve_phys(system, planet, times, edepth=fpfs, day2night=1.0, phase_offset=0, fig=fig, ax=ax)

'''With phase curve offsets '''
fig = plt.figure(figsize=(20,6))
ax = fig.add_subplot(111)

plot_starry_phase_curve_phys(system, planet, times, edepth=0.0 , day2night=0.0, phase_offset=10, fig=fig, ax=ax)
plot_starry_phase_curve_phys(system, planet, times, edepth=fpfs, day2night=0.0, phase_offset=10, fig=fig, ax=ax)
plot_starry_phase_curve_phys(system, planet, times, edepth=fpfs, day2night=1.0, phase_offset=10, fig=fig, ax=ax)
plot_starry_phase_curve_phys(system, planet, times, edepth=fpfs, day2night=1.0, phase_offset=50, fig=fig, ax=ax)
plot_starry_phase_curve_phys(system, planet, times, edepth=fpfs, day2night=1.0, phase_offset=75, fig=fig, ax=ax)
```

**Comment by rodluger** [comment]
@exowanderer I'll poke around your code a bit, but as per our conversation this morning, this is how you add a 30 degree longitudinal offset to the dipole map:
```python
map = starry.Map()
map[1, 0] = 0.5
map.axis = [0, 1, 0]
map.rotate(-30)
map.show()
```

**Comment by exowanderer** [comment]
I think that above code, using sins and cosines to modify the Y_1_0 Y_1p1. The code snippet above works to best of my desires. 

Published phase curve results also include a `A*sin(2*ang_freq*phase) + B*cos(2*ang_freq*phase)` term as well. With spherical harmonics, the next highest order would instead be `A*sin(longitude)**2 + B*cos(longitude)**2`. If there is a way to configure the physical input parameters into the double frequency (matching published results), then that would be a great addition to this wrapper as well.

Thank you for you help, in person and online
