### ISSUE TITLE
Spectral modeling of starspots

### ISSUE THREAD

**Issue by rodluger** [rodluger/starry#188]
@mrtommyb @christinahedges would like a simple working example of a rotating M dwarf with a cool spot from which we can generate time-dependent spectra. I'll put together a Jupyter notebook on this.

**Comment by gully** [comment]
Line 110 of `maps.py` has a note about how the Gaussians are assigned zero flux, so that the overall flux of a star remains the same when spots are added:

```python
def gaussian(sigma=0.1, lmax=10, res=500):
    """Return a spherical harmonic expansion of a Gaussian."""
    lon = np.linspace(-np.pi, np.pi, res * 2)
    lat = np.linspace(-np.pi / 2, np.pi / 2, res)
    lon, lat = np.meshgrid(lon, lat)
    z = np.cos(lat) * np.cos(lon)
    w = sigma ** -2
    norm = np.pi * BesselI(0, w)
    g = norm * np.exp((z - 1) / sigma ** 2)
    y = array2map(g, lmax=lmax)
    # NOTE: Force the constant term to zero so we
    # add no net flux. We need to think carefully
    # about this.
    y[0] = 0
    return y
```

While this choice of normalization may be desirable for certain applications, I can think of some---including starspot spectral modeling---in which you do not wish to renormalize in this way.  I have reassigned the intrinsic normalization `norm` to y[0], and find that it will likely work better for spot spectral modeling.

I am making a working example of spectral modeling of starspots with this revised normalization.

**Comment by gully** [comment]
(ping @mrtommyb @christinahedges )

**Comment by rodluger** [comment]
@gully Good point. Before you put too much work into this, check out the latest version of the `addSpot` method on the dev branch [here](https://github.com/rodluger/starry/blob/141903a21846d54aaf09aa95a3bcdd8b673ee116/include/starry/Map/public/oper.h#L65-L120). In this version (which I coded in C, so will be much, much, much faster) the gaussian spot integrates to `amp`, which I think is what you want. Here's the docstring:

```python
'''
Add the spherical harmonic expansion of a gaussian to the current
map. This routine adds a gaussian-like feature to the surface map
by computing the spherical harmonic expansion of a 3D gaussian
constrained to the surface of the sphere. This is useful for, say,
modeling star spots or other discrete, localized features on a
body's surface.

Args:
    amp (float or ndarray): The amplitude. Default 1.0, resulting \
        in a gaussian whose integral over the sphere is unity. For \
        spectral and temporal maps, this should be a vector \
        corresponding to the amplitude in each map column.
    sigma (float): The standard deviation of the gaussian. \
        Default 0.1
    lat (float): The latitude of the center of the gaussian \
        in degrees. Default 0.
    lon (float): The longitude of the center of the gaussian \
        in degrees. Default 0.
    lon (float): The longitude of the center of the gaussian \
        in degrees. Default 0.
'''
```

I'm hoping to release the next version in the next month or so, but it's already somewhat useable if you want to play around with it.
