### ISSUE TITLE
Reflected light

### ISSUE THREAD

**Issue by rodluger** [rodluger/starry#189]
I figured out the general expressions for the total flux visible from each polynomial term in the case that the disk is bounded by an elliptical terminator segment of semi-minor axis `b`. Assuming this is our geometry,

![image](https://user-images.githubusercontent.com/9323819/52796716-57c4c980-3042-11e9-89ac-eb2f24336bc1.png)

the expressions for the case where the planet is between new phase and half phase are

![image](https://user-images.githubusercontent.com/9323819/52796541-06b4d580-3042-11e9-9d02-ee33862bf2c8.png)

**Comment by rodluger** [comment]
All other phases can be obtained by combining rotations along with the expression for the integral over the full disk. The next step is to tackle the Hypergeometric function, which always simplifies to simple trig functions for the arguments above. I'll work on a recursion relation.

**Comment by rodluger** [comment]
Another note: the illumination factor under this geometry is `(1 - b) * y - b * z`.

**Comment by ericagol** [comment]
@rodluger Try making the substitution:

![image](https://user-images.githubusercontent.com/243664/52811380-ca857300-3049-11e9-9121-38e319320a96.png)

`y = \alpha \sqrt{1-x^2}`

in the inner integral.  Then, your integral becomes

![image](https://user-images.githubusercontent.com/243664/52811449-f9034e00-3049-11e9-8f28-b29cfb4afd44.png)

`\int_{-1}^1 dx x^i (1-x^2)^{j/2+1} \int_b^1 \alpha^j (1-\alpha^2)^{1/2} d\alpha`

which is separable into two integrals!  The second integral should be easy to integrate by parts, and thus derive a recursion relation (give me a few minutes).

**Comment by ericagol** [comment]
@rodluger Let:

![image](https://user-images.githubusercontent.com/243664/52812013-5a77ec80-304b-11e9-8112-2c7fa272b9b6.png)

`I_j(b) = \int_b^1 \alpha^j (1-\alpha^2)^{1/2} d\alpha`

Then, I find:

![image](https://user-images.githubusercontent.com/243664/52812062-75e2f780-304b-11e9-8d69-b0f8c8fc138e.png)

`I_j  = \frac{1}{j+2} \left[ b^{j-1}(1-b^2)^{3/2} + (j-1) I_{j-2}\right]`

which is your recursion relation!  The first integral integrates to the Gamma function term which you gave above.

**Comment by ericagol** [comment]
And, as you foresaw, the first two terms are straightforward:

![image](https://user-images.githubusercontent.com/243664/52812243-df630600-304b-11e9-9b36-7191dbf43c81.png)

`I_0  = \tfrac{1}{2} \left(-b\sqrt{1-b^2}+\cos^{-1} b\right)`

and

![image](https://user-images.githubusercontent.com/243664/52812291-fb66a780-304b-11e9-8a8c-8ebeed30ad0e.png)

`  I_1 =  \tfrac{1}{3} (1-b^2)^{3/2}`.
