### ISSUE TITLE
starry.Secondary's can have limb darkening values set, but they do not affect the final light curve.

### ISSUE THREAD

**Issue by christinahedges** [rodluger/starry#192]
I'm trying to build a light curve of an EB using starry. I'd like to use the starry.Kepler module so that I can use all the convenience functions for orbits. 

I set up my system with something like the following:
```python
pri = Primary(lmax=2)
pri[1:2] = 0.4, 0.26
sec = Secondary(lmax=2)
sec[1:2] = 0.4, 0.26
sys = System(pri, sec)
```

But when I calculate the light curve, the limb darkening coefficients on the secondary don't affect the result.

Is there a different way I should be modeling an EB? Thanks for any guidance!

**Comment by rodluger** [comment]
Can you post a snippet that reproduces the issue? Also, I'm surprised that `sec[1:2] = 0.4, 0.26` works, since the slice only las length 1, no?

**Comment by christinahedges** [comment]
Closing because it actually does work, it's just that the effect is much smaller than I thought!

```python
fig, ax = plt.subplots()
for ld in [[0.4, 0.26], [0., 0.]]:
    time = np.linspace(0, 2, 1000)
    pri = Primary(lmax=4)
    pri[1] = 0.4
    pri[2] = 0.2
    sec = Secondary(lmax=4)
    sec[1] = ld[0]
    sec[2] = ld[1]
    sys = System(pri, sec)

    sec.L = 0.2
    sec.r = 0.6
    sec.porb = 2
    sec.tref = 0
    sec.a = 4

    sys.compute(time)
    ax.plot(time, sys.lightcurve, lw=1, label='Limb Darkening: {}'.format(ld))
plt.legend()
plt.xlim(0.85, 1.15)
plt.xlabel('Time')
plt.ylabel('Flux')
```
![image](https://user-images.githubusercontent.com/14965634/53062150-a6c09380-3474-11e9-86d3-c6f17fdb70ff.png)

**Comment by rodluger** [comment]
I suspect it's a small effect because the radius of the occultor is so large! If you make the secondary larger than the primary, limb darkening will be much more pronounced.
