### ISSUE TITLE
Get autodiff working

### ISSUE THREAD

**Issue by rodluger** [rodluger/starry#2]
Ultimately we want to use starry for inference, so having analytic derivatives of the light curve will be super useful.

**Comment by ericagol** [comment]
I got autodiff working on the s_n(r,b) components.    I just finished coding up the s_n function in Julia, and I implemented autodiff using the ForwardDiff package.

I still haven't gotten the transformation and rotation matrices computed, but these should be straightforward.

**Comment by rodluger** [comment]
@ericagol Can you create a julia folder in the top level of the repository and place your code in there?

**Comment by ericagol** [comment]
Yes.  I just created a folder called julia/ at the top level of the repo where I placed this code and a preliminary README.md.

**Comment by rodluger** [comment]
Great, thanks!

**Comment by rodluger** [comment]
@dfm Autodiff is working **beautifully**! Thanks for the help.

**Comment by rodluger** [comment]
Currently computing gradients of the flux in [this test file](https://github.com/rodluger/starry/blob/e8156bec85a366c7dfc7bc12396bac5ad858aab1/starry/test_autodiff.cpp#L103). I'm going to add a gradient option to the pybind interface so we can start using this!

**Comment by rodluger** [comment]
@dfm How do I tell Eigen to not compute derivatives for a given variable? Say I have the function
```
template <typename T>
T testfunction(T& x1, T& x2, T& x3) {
    return x1 + x2 * x2 + x3 * x3 * x3;
}
```
and I want to compute derivatives w/ respect to `x1` and `x2`, but not `x3`. Because of the way I've templated this, all three must have the same type, so if `x1` and `x2` are `AutoDiffScalars`, so too must `x3`. A cryptic comment in [this example](http://eigen.tuxfamily.org/bz_attachmentbase/attachment.cgi?id=395),
```
/**
* Important note:
* All ActiveScalars which are used in one computation must have
* either a common derivative vector length or a zero-length
* derivative vector.
*/
```
led me to believe that I could just resize `x3.derivatives()` to size zero, but that leads to weird assertion errors. Any tips?

**Comment by rodluger** [comment]
@dfm OK, how insane is this? It compiles, runs, and does everything I want *starry* to do. The user provides a vector of strings called `gradient` with the names of the variables they want to differentiate, and the code declares them by setting the derivative number either within range of the number of derivatives (for Eigen to differentiate it) or outside of that range (which Eigen seems to treat as a constant):

```cpp
#include <iostream>
#include <iomanip>
#include <Eigen/Core>
#include <cmath>
#include <unsupported/Eigen/AutoDiff>
#include <vector>
using namespace std;
using Grad = Eigen::AutoDiffScalar<Eigen::VectorXd>;

// Dummy function
template <typename T>
T testfunction(T& x1, T& x2, T& x3, T& x4) {
    return x1 +
           x2 * x2 +
           x3 * x3 * x3 +
           x4 * x4 * x4 * x4;
}

// Instantiate a Grad type and give it a derivative number based on
// whether or not the user wants to compute its derivative.
Grad new_grad(string name, double value, vector<string>& gradients, int& ngrad) {
    if(find(gradients.begin(), gradients.end(), name) != gradients.end()) {
        return Grad(value, gradients.size(), ngrad++);
    } else {
        return Grad(value, gradients.size(), gradients.size());
    }
}

// Let's roll
int main() {

    // The user will supply this vector of parameter names
    // for which we will compute derivatives
    vector<string> gradients;
    gradients.push_back("x1");
    gradients.push_back("x4");

    // Declare our four parameters: only the ones the user
    // wants will be differentiated!
    int ngrad = 0;
    Grad x1 = new_grad("x1", 4., gradients, ngrad);
    Grad x2 = new_grad("x2", 3., gradients, ngrad);
    Grad x3 = new_grad("x3", 2., gradients, ngrad);
    Grad x4 = new_grad("x4", 1., gradients, ngrad);

    // Compute the function
    Grad result = testfunction(x1, x2, x3, x4);

    // Print the flux and all the derivatives
    cout << result.value() << endl;
    cout << result.derivatives() << endl;

    return 0;
}
```

The output is
```
22
1
4
```
which is what I'd expect, since
```
4 + 3^2 + 2^3 + 1^4 = 22
```
and
```
df/dx1 = 1
df/dx4 = 4 * x4^3 = 4
```

**Comment by rodluger** [comment]
Come to think of it, this smells like a memory leak to me... It's probably computing the other derivatives, but storing them in the segfault-prone limbo. Ther a got to be a better way to do this.

**Comment by rodluger** [comment]
@dfm I'm pretty sure there's a bug in Eigen: it's related to the reason we had to typecast many of the scalars in function calls to **step()** and the elliptic integrals to get the code to compile with autodiff. Check out [this open Eigen issue](http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1437) and the [corresponding code](http://eigen.tuxfamily.org/bz_attachmentbase/attachment.cgi?id=790).  I'm guessing what happens is that there's an issue with the * operator when the AutoDiffScalar variable has no derivatives. Long story short, if I change my function to
```
template <typename T>
T testfunction(T& x1, T& x2, T& x3) {
    return T(x1) + T(x2 * x2) + T(x3 * x3 * x3);
}
```
then everything works as expected. Here's a MWE:
```
#include <iostream>
#include <iomanip>
#include <Eigen/Core>
#include <cmath>
#include <unsupported/Eigen/AutoDiff>
#include <vector>
using namespace std;
using Grad = Eigen::AutoDiffScalar<Eigen::VectorXd>;

// Dummy function
template <typename T>
T testfunction(T& x1, T& x2, T& x3, T& x4) {
    // This leads to an "Assertion failed" error:
    //return x1 + x2 * x2 + x3 * x3 * x3 * x3 + x4;

    // This compiles and runs fine:
    return T(x1) + T(x2 * x2) + T(x3 * x3 * x3) + T(x4 * x4 * x4 * x4);
}

// Instantiate a Grad type with or without derivatives
Grad new_grad(string name, double value, vector<string>& gradients, int& ngrad) {
    if(find(gradients.begin(), gradients.end(), name) != gradients.end()) {
        return Grad(value, gradients.size(), ngrad++);
    } else {
        return Grad(value);
    }
}

// Let's roll
int main() {

    // The user will supply this vector of parameter names
    // for which we will compute derivatives
    vector<string> gradients;
    gradients.push_back("x1");
    gradients.push_back("x2");

    // Declare our parameters: only the ones the user
    // wants will be differentiated!
    int ngrad = 0;
    Grad x1 = new_grad("x1", 4., gradients, ngrad);
    Grad x2 = new_grad("x2", 3., gradients, ngrad);
    Grad x3 = new_grad("x3", 2., gradients, ngrad);
    Grad x4 = new_grad("x4", 1., gradients, ngrad);

    // Compute the function
    Grad result = testfunction(x1, x2, x3, x4);

    // Print the flux and all the derivatives
    cout << result.value() << endl;
    cout << result.derivatives() << endl;

    return 0;
}
```

**Comment by rodluger** [comment]
FYI: http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1281#c1

**Comment by dfm** [comment]
You definitely won't need to manually cast *everything* to `T`. The problem appears when you have inline operations on AutoDiffScalars. It is slightly annoying, but I think you'll be able to fix it pretty fast.

**Comment by rodluger** [comment]
@dfm Templates to the rescue! I think I found the ideal solution, which requires no hacky casting. The issue with Eigen is that there's a bug somewhere for dynamically-allocated derivative vectors, so the workaround is to declare all the types you might need ahead of time:
```cpp
using Grad1 = Eigen::AutoDiffScalar<Eigen::Matrix<double, 1, 1>>;
using Grad2 = Eigen::AutoDiffScalar<Eigen::Vector2d>;
using Grad3 = Eigen::AutoDiffScalar<Eigen::Vector3d>;
using Grad4 = Eigen::AutoDiffScalar<Eigen::Vector4d>;
```
Then, template the function that instantiates a GradX type:
```cpp
// Instantiate a Grad type with or without derivatives
template <typename T>
T new_grad(string name, double value, vector<string>& gradients, int& ngrad) {
    if(find(gradients.begin(), gradients.end(), name) != gradients.end()) {
        return T(value, gradients.size(), ngrad++);
    } else {
        return T(value);
    }
}
```
and the function that does the actual allocating/computing:
```cpp
// Compute the test function and its derivatives
template <typename T>
void compute(vector<string>& gradients){
    // Declare our parameters: only the ones the user
    // wants will be differentiated!
    int ngrad = 0;
    T x1 = new_grad<T>("x1", 4., gradients, ngrad);
    T x2 = new_grad<T>("x2", 3., gradients, ngrad);
    T x3 = new_grad<T>("x3", 2., gradients, ngrad);
    T x4 = new_grad<T>("x4", 1., gradients, ngrad);

    // Compute the function
    T result = testfunction(x1, x2, x3, x4);

    // Print the flux and all the derivatives
    cout << result.value() << endl;
    cout << result.derivatives() << endl;
}
```
Then, all you need is an if-then-else to capture all the cases:
```cpp
// Let's roll
int main() {

    // The user will supply this vector of parameter names
    // for which we will compute derivatives
    vector<string> gradients;
    gradients.push_back("x1");
    gradients.push_back("x2");

    if (gradients.size() == 1) compute<Grad1>(gradients);
    else if (gradients.size() == 2) compute<Grad2>(gradients);
    else if (gradients.size() == 3) compute<Grad3>(gradients);
    else if (gradients.size() == 4) compute<Grad4>(gradients);

    return 0;
}
```
This compiles and works like a charm! I'm attaching the code for future reference.
[test_autodiff.txt](https://github.com/rodluger/starry/files/1968132/test_autodiff.txt)

**Comment by rodluger** [comment]
@dfm Dude:
![image](https://user-images.githubusercontent.com/9323819/39591914-183932a2-4eba-11e8-8c49-4df1c42d29d1.png)

**Comment by ericagol** [comment]
Shouldn’t we be saying “Doctor” rather than “Dude”?

That looks great!

Eric Agol
Astronomy Professor
University of Washington

**Comment by rodluger** [comment]
@dfm This is how I'm currently structuring the code:
```python
>>> import starry

>>> map1 = starry.Map()

>>> map1[1, 0] = 1

>>> map1.flux(axis=(0, 1, 0), theta=0.3, xo=0.1, yo=0.1, ro=0.1)

0.9626882655504516

>>> map2 = starry.grad.Map()

>>> map2[1, 0] = 1

>>> map2.flux(axis=(0, 1, 0), theta=0.3, xo=0.1, yo=0.1, ro=0.1)

array([[ 9.62688266e-01,  4.53620580e-04,  0.00000000e+00,
        -6.85580453e-05, -2.99401131e-01, -3.04715096e-03,
         1.48905485e-03, -2.97910667e-01]])
```

The modules `starry` and `starry.grad` are compiled from the same chunk of code, but with a healthy sprinkling of `#ifdef STARRY_AUTODIFF` to handle `AutoDiffScalar`-specific implementation stuff. They therefore have all the same classes, methods, properties, and docstrings, but their outputs are of course different. To get this to work, I'm `#include`ing that chunk of code twice, once with `STARRY_AUTODIFF` undefined, and once with it defined.

What do you think of this? It certainly hasn't helped my code legibility...

**Comment by rodluger** [comment]
Quick update on this. I'm slowly getting things to work with dynamically-sized derivative vectors, which is the ideal way to do this. The most important thing I've learned is that casting to type `T` is not enough, since type `T` has an `Eigen::Dynamic` vector length. I need to actually force the derivative vector of all intermediate variables -- and all function outputs -- to have the correct length. For instance, the following line in `flux()` doesn't work:
```
if (b <= ro - 1) return 0;
```
nor does
```
if (b <= ro - 1) return T(0);
```
since neither allocates space for the derivatives of the result. What I have to do is this:
```
if (b <= ro - 1) return 0 * ro;
```
where `ro` is one of the variables I'm differentiating.

For some reason I no longer get *any* compiler errors -- just segfaults when I finally run the code. Debugging this is therefore super tedious. But I'm getting the hang of it.

**Comment by dfm** [comment]
That does sound tedious! Let me know if there's anything that I can do to help out.

**Comment by rodluger** [comment]
Got the flux calculation to work all the way through! Now the user can dynamically choose which and how many derivatives to compute. Gonna take a while for me to clean the code up and push to the master branch, but I think it's downhill from here!

**Comment by rodluger** [comment]
Quick update on this: I'm switching back to compile-time defined derivative vector sizes. `AutoDiffScalar<VectorXd>` is riddled with issues *and* it's **20-30 times slower** than the same calculation with fixed-size derivative vectors. It's actually more efficient to compute **all** derivatives and let the user choose which ones to output than to selectively compute only a few derivatives.

**Comment by rodluger** [comment]
@dfm @ericagol Just need to write it up!
![image](https://user-images.githubusercontent.com/9323819/39881068-9164bbf4-5434-11e8-978a-ad7553831474.png)

**Comment by rodluger** [comment]
Closing this issue. There are things that can still be optimized, but I'm happy!
