### ISSUE TITLE
Speed up the limb darkening calculations

### ISSUE THREAD

**Issue by rodluger** [rodluger/starry#20]
Currently, the calculation for a quadratically limb-darkened star is about 6 times slower than batman:
![image](https://user-images.githubusercontent.com/9323819/37632605-5136cabe-2bac-11e8-9579-2f76f8f0ecf8.png)

Batman currently uses a [polynomial approximation](https://github.com/lkreidberg/batman/blob/master/c_src/_quadratic_ld.c#L304) to the elliptic integrals of the first and second kind, so that could be accounting for most of that difference. Another factor is that I'm currently computing *all* terms in the solution vector up to lmax=2. We only need the m = 0 terms for limb-darkened stars. I tried to prevent computation of m!=0 terms when limb darkening is applied but got weird results. Stay tuned.

**Comment by rodluger** [comment]
Currently, the calculation for a quadratically limb-darkened star is about 6 times slower than batman:
![image](https://user-images.githubusercontent.com/9323819/37632605-5136cabe-2bac-11e8-9579-2f76f8f0ecf8.png)

**Comment by ericagol** [comment]
Is Batman using the ellpi_bulirsch code?

**Comment by rodluger** [comment]
[Yes](https://github.com/lkreidberg/batman/blob/master/c_src/_quadratic_ld.c#L265)

**Comment by rodluger** [comment]
OK, I'm now computing only the terms of the solution vector **s^T** that we actually need. Switching to the polynomial approximation of the elliptic integrals doesn't help significantly. The difference in speed between starry and batman is now a factor of 4, which is better, but I suspect we can improve this even more.

Things to consider:
   - Inline functions?
   - Tabulate the binomial coefficient? I'm tabulating the factorials, so this would save us two multiplications and one division every time we call `fact::choose(i, j)`. This is called a lot, so maybe this could help a bit
   - Black magic?

**Comment by ericagol** [comment]
@rodluger 

My Julia code seems comparable or a bit faster than Batman (although I'm only computing linear limb-darkening case, but I am computing the full elliptic integrals), although I'm not sure what is going on with the 10-point case.  Could there be some overhead to calling C from Python?

![quadratic_timing_julia](https://user-images.githubusercontent.com/243664/37671386-d87de184-2c28-11e8-8241-5fc1d5873923.png)

**Comment by rodluger** [comment]
There's definitely some overhead, but Laura also wraps her C in Python (though not with Pybind, so there may be a slight difference).

It's more likely to be due to the overhead of doing the calculations on spherical harmonics. Our linear limb darkening term is probably similar in speed, but my quadratic term requires some recursion to evaluate -- it's not a one-liner like in batman. I tried making all my functions inline but didn't see a speed boost.

@dfm, any suggestions? I added section 7.7 on speed tests to the paper, with links to the scripts so you can check it out if you have time.

**Comment by rodluger** [comment]
I still haven't been able to get within better than a factor of 4-5 of batman. I'm going to code up a separate module to do stellar transits, which should remove most of the overhead.

**Comment by rodluger** [comment]
Ok, it worked. I stripped the quadratic limb darkening calculation of all the overhead, and now we are within a factor of ~2, so I'm happy, especially because our expressions are more stable! If I use the polynomial approximation to the elliptic integrals like Laura does, then I get to within a factor of ~1.5.

**Comment by rodluger** [comment]
Woot:

![image](https://user-images.githubusercontent.com/9323819/38460431-75fa2bea-3a6e-11e8-8dd9-a7c67eb6146d.png)
