### ISSUE TITLE
Star with nonzero inclination

### ISSUE THREAD

**Issue by bmorris3** [rodluger/starry#200]
Hey @rodluger, 

I'm working on fitting a light curve of a planet transiting a spotted star. I can approximate the star using `starry`, but I may be hitting a snag or a hole in the documentation, and I could use your help to figure out which is which. 

I know the positions of the starspots in latitude and longitude in the host star's coordinates, and when I specify them with `add_gaussian` they're placed on the star as though its stellar inclination is aligned with \hat{y}. Is it possible to place spots on a star which is inclined at an arbitrary angle? I see that you can rotate the star about an arbitrary axis with `map.axis`, but I don't know if I can rotate the positions fed to `add_gaussian`, if that makes sense.

Thanks!

**Comment by rodluger** [comment]
Hey, yes, that's an issue with `starry`. I fixed it in the `dev` version, but what you could do for now is add the spots where you want them and *then* incline the star. Here's an example:

```python
inc = 60
lat = -20
lon = 45
map = starry.Map(10)
map.add_gaussian(lat=lat, lon=lon)
map.axis = [1, 0, 0]
map.rotate(90 - inc)
map.axis = [0, np.sin(inc * np.pi / 180), np.cos(inc * np.pi / 180)]
```

I first dded the spot in the frame where the axis is aligned with `yhat`, then I rotate the map about the x axis to incline it, and finally set the rotation axis vector accordingly.

Does this help?

**Comment by bmorris3** [comment]
Thanks, that helps. One more question – how can I add limb darkening on the same map, in your example? Right now, if I try: 
```python
map[1] = 0.5
```
I get 
```
RuntimeError: Degree of the limb-darkened map exceeds `lmax`. All coefficients have been reset.
```

**Comment by rodluger** [comment]
Do
```
map.add_gaussian(lat=lat, lon=lon, lmax=9)
```
to limit the degree of the expansion of the spot to 9, so you have 1 degree left for limb darkening.

This also changes in the next version -- you'll be able to separately set the Ylm and LD degrees. Also, note that the limb darkening prescription in `v0.3.0` [is slightly wrong](https://github.com/rodluger/starry/blob/dev-stale/notebooks/LDNormalization.ipynb). I also fixed this in the dev version. I'm hoping for a release by the end of the summer, so stay tuned.

**Comment by bmorris3** [comment]
Awesome. Ok one last question – is the `sigma` parameter in units of radians?

**Comment by rodluger** [comment]
Hmmm I can't remember, and it doesn't look like I documented it. You could probably figure that out by adding spots of different sizes at `lat, lon = (0, 0)` and plotting the intensity (```map(y=0, x=0, theta=np.linspace(0, 360, 1000)```) along the equator for each map, and comparing it to a gaussian. If you have time to do this, I'd be curious to know the answer!
