### ISSUE TITLE
Theano warnings

### ISSUE THREAD

**Issue by rodluger** [rodluger/starry#208]
This warning pops up all over the place because of issues in Theano. Currently it's not leading to any errors but we should either patch Theano or think of a workaround for this.
```
/anaconda3/lib/python3.7/site-packages/theano/tensor/subtensor.py:2339: FutureWarning: Using
a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead
of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which
will result either in an error or a different result.
```

**Comment by dfm** [comment]
I think this is already fixed in Theano on GitHub and it'll come out with the next release.

**Comment by rodluger** [comment]
I issued two PRs ([here](https://github.com/Theano/Theano/pull/6708), [here](https://github.com/Theano/Theano/pull/6703)) to Theano and those have been merged, but this warning occurs at a different place in the Theano code. I'll poke around and issue another PR if necessary. @dfm, do you know when the next release is planned?

**Comment by dfm** [comment]
I think this is the relevant PR: https://github.com/Theano/Theano/pull/6711

But looks like it hasn't been merged yet.

**Comment by rodluger** [comment]
I think these warnings have all been fixed on the master branch of Theano, but they haven't issued a new release of the code since January of last year. @dfm do you know if they plan on releasing a patch? There have been lots of PRs since the last release. Also, do you ever get these warnings with exoplanet?

**Comment by dfm** [comment]
Theano won't be making *any* new releases, but I'm helping out with the pymc-devs/Theano-PyMC fork that will (hopefully) make releases.

**Comment by rodluger** [comment]
I believe the last version of Theano (`1.0.5`) fixes all of these.
