### ISSUE TITLE
Movie generation for pymc3 starry models

### ISSUE THREAD

**Issue by christinahedges** [rodluger/starry#226]
Hiya, 

It would be useful to be able to use the `show` method on starry models created with pymc3. At the moment this throws an error:

```python
with model:
     sys.show(t=0)
```

**Comment by rodluger** [comment]
@christinahedges  You're not going to believe this but I'm finally implementing this in #270, to be merged into master soon. This will work as long as you provide a point, i.e.,

```python
with model:
    sys.show(t=0, point=model.test_point)
```

For now this is on the branch `restructure`. Give it a spin if you're interested and let me know if it works for you! No rush.
