### ISSUE TITLE
nexsci extensions failing

### ISSUE THREAD

**Issue by rodluger** [rodluger/starry#233]
@christinahedges can you look into this? https://dev.azure.com/rodluger/starry/_build/results?buildId=868&view=ms.vss-test-web.build-test-results-tab

**Comment by christinahedges** [comment]
The extension is trying to query the exoplanet archive to download data. It might have been down this morning, I'm hearing other people having trouble too today. Is it possible to rerun the test? If it still fails, I'll remove that test.

**Comment by rodluger** [comment]
I just re-ran it, still failing. It's been doing this since last week at
least. No need to remove the test. Is there someone we should contact about
this?

**Comment by christinahedges** [comment]
So when I run this test locally (cd in to the `extensions/tests/greedy` directory and run `pytest test_greedy_nexsci.py`) this runs for me and passes. Can you also try running it locally to double check? It could be something with the CI not being able to run the query to nexsci.

**Comment by rodluger** [comment]
Good point. It works for me locally as well. The issue is actually in a [recent update to OpenSSL](https://github.com/urllib3/urllib3/issues/1825). Not sure how best to handle this, except to sit tight and wait for a fix in pyOpenSSL or urrlib. It looks like this is breaking lots of codes.

**Comment by christinahedges** [comment]
Ooh wow good find. I feel that these tests could totally be skipped for a few months if you didn't want to wait around, they are just checking to see if data can be requested from NExSci and if we can both run it locally it seems silly for this to hold up starry.

**Comment by rodluger** [comment]
This seems to be working now!
