### ISSUE TITLE
Keyword missing in `render` when `reflected` is True on secondary map

### ISSUE THREAD

**Issue by christinahedges** [rodluger/starry#243]
**Describe the bug**
When there is a secondary map with `reflected=True`, I can't use `sys.show()` without an error message. It seems like one of the keyword arguments isn't set in `render` in this case.

**To Reproduce**
```python
import starry
import numpy as np
starry.config.lazy = True
starry.config.quiet = True

sec_map = starry.Map(ydeg=1, reflected=True, amp=0.1, inc=90, 
        )
sec_map[1:, 0] = -1

sec = starry.Secondary(sec_map,
        r=1,
        inc=90,
        porb=10,
        prot=10,
        t0=0,
    )

# Primary
pri_map = starry.Map(udeg=1, amp=1)
pri_map[1] = 0.8
pri = starry.Primary(
    pri_map,
    r=1)

sys = starry.System(pri, sec)

sys.show(t=np.linspace(-5, 5, 100), window_pad=3.75, figsize=(5, 5))
```

**Expected behavior**
When reflected is set to `False` the above snippet works fine.

**Your setup (please complete the following information):**
 - Version of starry: 1.0.1.dev49+g871582f6
 - Operating system: Mac OS Mojave
 - Python version & installation method (pip, conda, etc.): github

**Additional context**

I get the following error message
```python
TypeError: render() missing 1 required positional argument: 'RsN'
```

**Comment by rodluger** [comment]
Thanks for finding this. Can you confirm you get the expected behavior now?

**Comment by rodluger** [comment]
FYI I found an unrelated bug also affecting `sys.show()` when the secondary units are not solar. I don't know if you've ever changed `length_unit` in a Secondary instance, but if so, the rendering would have been wrong. [This commit](https://github.com/rodluger/starry/commit/225dffadab9dc27211e0c7044081cc2762b90ed5) fixes it, I think.
