### ISSUE TITLE
Pre-compiled Mandel & Agol routine?

### ISSUE THREAD

**Issue by ethankruse** [rodluger/starry#249]
Hey,

I'm upgrading my planet search into a proper pip-installable package and doing improvements along the way. One part of that is looking to use starry for Mandel & Agol light curve models instead of batman like I've been using because of the improved numerical stability stuff. The problem I'm running into is that it seems to require a "flux" routine to be compiled at the very least every time the package is imported. That's a 10+ second operation, and if that's required to be run every time I search a star, that's going to add up and may not be worth it.

Here's how my code is currently set up:

```
import warnings
import numpy as np

import starry
starry.config.lazy = False
star = starry.Map(udeg=2)
# don't bother with the theano warnings
with warnings.catch_warnings():
    warnings.filterwarnings("ignore", category=FutureWarning)
    # compile the flux routine once on loading the package instead
    # of every call to mandel_agol
    star.flux(xo=0, yo=0, zo=1, ro=0.1)

def mandel_agol(bs: np.ndarray, u1: float, u2: float, r2r1: float):
    star[1:3] = [u1, u2]
    # don't bother with the theano warnings
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=FutureWarning)
        return star.flux(xo=0, yo=bs, zo=1, ro=r2r1)
```

I originally was creating a new Map() object in every call to mandel_agol, but that forced a compilation every function call. So I moved a single object outside the function definition, and that top bit calls star.flux for no reason except to compile the code when I import the file so that future calls in the python session can call mandel_agol without the compilation delay. But if I send off 100 processes to search 100 stars, and each one has to pause for 10 seconds as I import the package to wait for that function to compile, that adds up quickly.

So I guess my question is:

1. Am I missing anything in starry that already exists to avoid this?

2. Is it possible to create a "Mandel & Agol" class that is compiled only once when the package is installed (or the function is first called after installation), but never again? starry is an amazing package with lots of bells and whistles, but a simple quadratic limb darkened Mandel & Agol routine is never going to go out of style. Is there any other python version of Mandel & Agol besides batman that people use? As far as I know, starry is the only robust one without all the numerical issues, so exposing a simple pre-compiled mandel_agol function for people like me to get quick values would be valuable.

**Comment by rodluger** [comment]
That's a good question. One thing you could try is to compile the `theano` function for computing the flux yourself:

```python
import theano
import theano.tensor as tt
import starry

starry.config.lazy = True

bs = tt.dvector()
u1 = tt.dscalar()
u2 = tt.dscalar()
r2r1 = tt.dscalar()

def _func(bs, u1, u2, r2r1):
    star = starry.Map(udeg=2)
    star[1:] = [u1, u2]
    return star.flux(xo=0, yo=bs, zo=1, ro=r2r1)

mandel_agol = theano.function([bs, u1, u2, r2r1], _func(bs, u1, u2, r2r1))
```

Then, instead of importing starry and instantiating a `Map`, just pass the `mandel_agol` object to each of the nodes. It's a self-contained compiled function with no overhead, and you can call it just like the version in your code snippet above.

Would this work?

**Comment by ethankruse** [comment]
Asked this right before I went on vacation and got sucked into other things, but I'm back on this issue.

So my thought of a solution was to pickle the compiled function, so that I could create it once. Then later times just load the pickle, which I thought would be fast. Trying to pickle the starry.Map object failed, but for some reason pickling your function works. However, it seems like theano is doing something weird because just trying to load the pickle back up takes as long as compiling it to begin with (~10 seconds). I tried both standard python pickle and theano's own pkl_utils with the same results.

Here's the load code that just loads your theano.function from above that I had saved in a pickle.

```
import time
import theano.misc.pkl_utils

t1 = time.perf_counter()
with open(_ma_pickle, 'rb') as ff:
    compiled_mandel_agol = theano.misc.pkl_utils.load(ff)
t2 = time.perf_counter()
print(f'elapsed: {t2-t1}')

>>> elapsed: 10.932560602
```

So none of this seems to solve the problem that every time I start a new python instance and try to import my package, it takes 10+ seconds purely because of something about this mandel_agol function. 

Do you have any idea what theano might be doing when it loads a pickle? Is there a way to save whatever it compiles as a standalone executable or something that doesn't have to be reconfigured/recompiled every time it's loaded?

**Comment by rodluger** [comment]
Interesting. I'm not sure why the pickle takes so long to load. @dfm any ideas? You must run into similar issues with exoplanet.

I certainly didn't design starry with this in mind -- it should really only be imported once, and maps should only be instantiated a single time, then re-used as often as you need them. That said, the code that computes the Mandel and Agol routine is (relatively) simple. If Dan doesn't have a better solution, I could spend a couple hours next week to carve out the relevant sections and compile it into a shared library with negligible overhead.

**Comment by ethankruse** [comment]
Hey, any chance you or @dfm have any new suggestions here (once the segfault bit is fixed)?

I'd still like to get the full precision/accuracy of the new Mandel & Agol implementation without having to wait 10+ seconds for a compilation. Any sort of precompiled version would be amazing.

**Comment by dfm** [comment]
Can you say a few more words about how you're "sending off" your processes? Are you currently manually pickling the function then loading it in each process? Or are you using multiprocessing?

Also: what features do you need? If you just need a limb darkened light curve (rather than the full spherical harmonic model) you could take a look at the (soon to be released) [precompile branch of exoplanet](https://github.com/exoplanet-dev/exoplanet/tree/precompile). It's buried deep, but you could use something like:

```python
cl = the C_l coefficients from Agol+ 2020
b = array of "impact parameters" (star/planet projected separation)
r = array of radius ratios, same shape as b

los = np.ones_like(r)
f = np.empty_like(b)
dfdcl = np.empty(cl.shape + b.shape)
dfdb = np.empty_like(b)
dfdr = np.empty_like(b)

ld.apply(cl, b, r, los, f, dfdcl, dfdb, dfdr)

# now f is the light curve
```

**Comment by dfm** [comment]
@ethankruse I also just pushed [a commit](https://github.com/exoplanet-dev/exoplanet/commit/865409ecfbe38f64fc6029731ce15f4a7a45e3ed) to that exoplanet branch that might make what you need easier. Here's how you would use it:

```python
from exoplanet.theano_ops.driver import SimpleLimbDark
ld = SimpleLimbDark()
ld.set_u([0.3, 0.2])  # These are the "u" coefficients, not C_l

relative_flux = ld.apply(b, r)  # Where b and r are the same as above, but it'll handle basic broadcasting
```

I've tested that this pickles properly too.

**Comment by ethankruse** [comment]
Thanks Dan, that last bit looks promising. Essentially all I'm looking for is a fast quadratic limb-darkening Mandel & Agol model for my package. Such that I can just give it u1/u2/r2r1 over a range of impact parameters and it gives me the light curve back. Packages don't seem to want to just give you that, they want you to load up whole machinery and simulate entire orbital systems or whatever. I've been using batman, and I had to dig into their protected functions to find the simple implementation I was looking for rather than loading up an entire planetary system model or whatever framework they use:

```
def mandel_agol(zs, u1, u2, r2r1, nthreads=1):
    # I noticed this was necessary at one point, not sure if this bug was ever fixed
    zs = np.ascontiguousarray(zs)
    return batman._quadratic_ld._quadratic_ld(zs, r2r1, u1, u2, nthreads)
```

I don't particularly care about the threading, but it was an option in batman. The use case is that then anywhere in my code I need a transit model of some particular shape, I just call

```
import qats
qats.mandel_agol(...)
```

Over the years I've noticed some weird edge cases from batman where things don't look right. And in writing unit tests for my code I realized the batman M&A blows up in weird situations. I recall Eric saying that this was fixed in starry (and my tests indicate this is largely true) so I wanted to use that as a drop-in replacement; that led to this issue that using the basic starry M&A incurs a 10 second compile cost every time you import the package, which defeats the whole purpose of a lean, fast, simple M&A function.

**Comment by rodluger** [comment]
@ethankruse I'm going to close this issue in favor of the implementation in exoplanet. Let's chat more in exoplanet-dev/exoplanet#122.
