### ISSUE TITLE
TypeError: cannot pickle 'starry._c_ops.Ops' object

### ISSUE THREAD

**Issue by fbartolic** [rodluger/starry#254]
The eclipsing binary example notebook with MCMC is failing at the NUTS sampling step. It has something to do with the new version of PyMC3 (3.9) because it works fine with PyMC3 3.7.

The following cell fails with the error `TypeError: cannot pickle 'starry._c_ops.Ops' object`:
```
with model:
    trace = pm.sample(
        tune=500,
        draws=500,
        start=map_soln,
        chains=4,
        step=xo.get_dense_nuts_step(target_accept=0.9),
    )
```
It works if you set `chains=1`. 

Starry version: `1.0.1.dev161+g9c462a2c`
exoplanet version: `0.3.3`
PyMC3 version: `3.9.3`
macOS Catalina
install from source

**Comment by dfm** [comment]
`forkserver` strikes again!

pymc-devs/pymc3#3844

**Comment by dfm** [comment]
It's all the same issue and it's really a Python issue, not pymc3 really. I've found that using fork instead of forkserver works fine in general.

**Comment by rodluger** [comment]
What's the exact workaround? Specifying `mp_ctx="forkserver"` in `pm.sample`?

**Comment by dfm** [comment]
Yes - I expect that that will do it.

**Comment by fbartolic** [comment]
> Looking at @bmorris3's comment, the workaround is
> 
> ```python
> import multiprocessing as mp
> 
> pm.sample(
>     ..., 
>     mp_ctx=mp.get_context("fork")
> )
> ```

Thanks for the fix, this works!

**Comment by rodluger** [comment]
FYI I'm implementing simple pickling support in #270, to be merged into master soon. Should fix this issue without needing to switch to ``fork``.
