### ISSUE TITLE
Error building wheel on installation with Windows 10

### ISSUE THREAD

**Issue by jessica553** [rodluger/starry#257]
Hi, I'm trying to install starry which is new to me, and I've got this error message:
ERROR: Command errored out with exit status 1:
   command: 'c:\users\jessica\anaconda3\python.exe' 'c:\users\jessica\anaconda3\lib\site-packages\pip\_vendor\pep517\_in_process.py' build_wheel 'C:\Users\Jessica\AppData\Local\Temp\tmp987n5aht'
       cwd: C:\Users\Jessica\AppData\Local\Temp\pip-install-ekh4vrxn\starry

At the end of the error message it says this:

 error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.27.29110\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for starry
Failed to build starry
ERROR: Could not build wheels for starry which use PEP 517 and cannot be installed directly

Is this something thats come up before? Is there a solution you could point me to? 

I'm tagging @sarahmartell as I'm working on this project with her.

**Comment by rodluger** [comment]
Hi @jessica553 I have some pre-compiled wheels for Windows you could try. Go [here](https://dev.azure.com/rodluger/starry/_build/results?buildId=1202&view=artifacts&type=publishedArtifacts) and click on the drop down menu next to "drop" and select "Download artifacts":

![image](https://user-images.githubusercontent.com/9323819/94437211-6e625a80-016b-11eb-8f3f-48686253f067.png)

You'll get a zip file with a bunch of wheels:

![image](https://user-images.githubusercontent.com/9323819/94437317-95b92780-016b-11eb-8879-767c2d31d2bd.png)

Select one of the "win" ones according to your machine (32 or 64 bit) and your python installation (3.6, 3.7, or 3.8). Copy that file name and then do

```
pip install wheel
pip install starry-1.0.1.dev124+gcfe1eca8-cp38-cp38-win_amd64.whl
```

(e.g., if you're on a 64 bit machine running Python 3.8).

Let me know if that works. I've been working on the next release of `starry` -- when that comes out you should be able to install `starry` the easy way.

**Comment by SarahMartell** [comment]
Thanks @rodluger ! We'll let you know how we go with this.

**Comment by jessica553** [comment]
It works @rodluger, thanks!

**Comment by rodluger** [comment]
Awesome, glad to hear.
