### ISSUE TITLE
map.load() crashes with healpy 1.14.0

### ISSUE THREAD

**Issue by fbartolic** [rodluger/starry#259]
Just for reference, `map.load()` crashes on my machine with healpy `1.14.0`, it works with `1.13.0`. Here's a reproducible example:
```Python
import numpy as np
import starry
starry.config.lazy = False

img = np.random.uniform(0.4, 0.5, size=((2963, 5926)))
map = starry.Map(ydeg=20, reflected=True)
map.load(img, force_psd=False)
```
[This fix](https://stackoverflow.com/questions/53014306/error-15-initializing-libiomp5-dylib-but-found-libiomp5-dylib-already-initial) seems to work:
```Python
import os
os.environ['KMP_DUPLICATE_LIB_OK']='True'
```
Either that or stick to healpy `1.13.0`.

 - Version of starry: '1.0.1.dev168+gf22bf764.d20201116'
 - Operating system: MacOS Catalina
 - Python version & installation method (pip, conda, etc.): latest from repo

**Comment by rodluger** [comment]
Thanks for submitting this! I just upgraded to Catalina and I'm running into the same issue in a totally different context (outside of `starry`, but still in a `theano`-based code). It does seem to be a Mac issue. I'll try to dig a little deeper to see if there's a better fix.

**Comment by rodluger** [comment]
I'm going to remove the `healpy` dependency in the next release, since this is in fact the source of all of the OpenMP errors I'm getting. Stay tuned.
