### ISSUE TITLE
Better error handling

### ISSUE THREAD

**Issue by rodluger** [rodluger/starry#26]
Most of the errors thrown in *starry* are sloppy and look like [this](https://github.com/rodluger/starry/blob/master/starry/solver.h#L199), where I print to screen with `std::cout` and abort with `exit(1)`. It would be much nicer to have a central logging system with error codes and such. I defined a few error codes [here](https://github.com/rodluger/starry/blob/master/starry/constants.h#L67) but this needs to be done more consistently throughout the code.

@dfm, is there a good C++ library for error handling/logging we could use?

**Comment by dfm** [comment]
Take a look [here](http://lmgtfy.com/?q=c%2B%2B+exceptions)...

(it's in the standard library 😄)

**Comment by dfm** [comment]
PS and pybind11 automatically converts C++ exceptions to Python exceptions.

**Comment by rodluger** [comment]
Lol. Thanks :)

**Comment by rodluger** [comment]
@dfm How should I handle warnings? Is there a way to throw a python RuntimeWarning?

**Comment by rodluger** [comment]
I'm mostly happy with the error handling, so I'm gonna close this.
