### ISSUE TITLE
[question] simulating a star with a transiting brown dwarf

### ISSUE THREAD

**Issue by jpdeleon** [rodluger/starry#260]
I would like to simulate a population of systems composed of a star and a transiting brown dwarf.

**Describe the solution you'd like**
I wonder if the `starry.System` can be used to simulate such systems using the procedure described in the [eclipsing binary system tutorial](https://luger.dev/starry/latest/notebooks/EclipsingBinary_Generate.html). Is it correct to just assume a small `amp` and `u`=0 for the `starry.Secondary` component to simulate a brown dwarf companion?

**Comment by rodluger** [comment]
@jpdeleon I don't see why not! Let me know if you run into issues.
