### ISSUE TITLE
Execution time of map.minimize() increases with number of calls

### ISSUE THREAD

**Issue by rychallener** [rodluger/starry#268]
**Describe the bug**
The execution time of map.minimize(), or at least the evaluation of the theano objects, increases substantially with number of function calls. The first few iterations take a fraction of a second (aside from overhead of the first call), but can take over 3 seconds by the 500th call. The problem can be reduced by re-initializing the map, but that requires its own overhead.

**To Reproduce**
```
import starry
import time
import numpy as np
import matplotlib.pyplot as plt

ydeg = 1

map = starry.Map(ydeg=ydeg)

niter = 500

times = np.zeros(niter)

for i in range(niter):
    yval = np.random.randn((ydeg+1)**2-1)
    map[1:,:] = yval
    tic = time.time()
    lat, lon, _ = map.minimize()
    lon.eval()
    times[i] = time.time() - tic
    print("Iter {}: {} seconds".format(i, times[i]))

plt.plot(np.arange(niter), times)
plt.show()
```
**Expected behavior**
I expected the function to have a (somewhat) consistent runtime. 

**Your setup (please complete the following information):**
 - Version of starry: 1.0.1.dev186+gfac89fad (current master)
 - Operating system: Ubuntu 20.04.02 LTS
 - Python version & installation method (pip, conda, etc.): python 3.8.5, cloned from github and installed with pip inside a conda environment

**Additional context**
Theano version 1.0.5

Figure produced by the above code:
![minimization-time](https://user-images.githubusercontent.com/11049765/108522522-e9ebb200-729a-11eb-819e-d0c56eb1b028.png)

**Comment by rodluger** [comment]
Interesting. I'm working on a new release of `starry` to fix a ton of issues (mostly done -- expect to have it out next week) so I'll add this to the list. Out of curiosity, what's the behavior when `lazy=False`?

**Comment by rychallener** [comment]
Oh interesting. That runs *much* faster and the evaluation time is quite consistent. With lazy=False, average evaluation time over 10000 iterations is 0.003 seconds, ignoring the overhead of the first iteration.

**Comment by rodluger** [comment]
I think this is probably expected behavior then (although of course it's not ideal!) When you're in lazy mode, theano just keeps adding stuff to the computational graph at every iteration of the for loop. So even though you're re-assigning all of the coefficients of the map with `map[1:,:] = yval`, theano "remembers" every past assignment, so internally it needs to traverse longer and longer graphs with every loop. When you compile the function, however (with `lazy=False`), that all gets optimized away.

Calling `eval()` is really only a good idea for debugging or if you only do it a single time. If you find yourself doing it a lot, you'll *always* get a huge computational benefit from switching to greedy mode or explicitly compiling your expression as a theano function.

Let me know if this fixes the issue for you.

**Comment by rychallener** [comment]
Ah I see. Thanks for your help. I didn't realize that theano tracks assignments. I try not to frequently evaluate the expressions, but in this case I think it's unavoidable, so I'll experiment with greedy mode or a theano function.

**Comment by rodluger** [comment]
Can you tell me a bit more about your specific use case?

**Comment by rychallener** [comment]
Broadly, I'm working with Emily Rauscher on an extension of her "eigenmap" planet mapping technique. I think you've been in contact with her about related work? My application is similar to hers, but with the goal of eventually combining spectroscopic eigenmaps vertically in a planet's atmosphere and retrieving three-dimensional structure. I'm using starry to generate the spherical harmonics light curves and then evaluate the eigenmaps after I've done fits to each spectroscopic light curve.

In the particular application that prompted this issue, I have an MCMC posterior distribution of map coefficients and want to generate a distribution of hotspot locations. I'm doing this by using map.minimize() on the maps with negated coefficients to find the maximum. So I need to minimize tens to hundreds of thousands of maps, which was pretty daunting at several seconds per evaluation.

**Comment by rychallener** [comment]
This is likely due to my unfamiliarity with theano, but I'm having trouble creating a function to run the minimization. Here's my attempt at a basic implementation:

```
import starry
import theano
import theano.tensor as tt
import numpy as np

def hotspotlon(yval):
    map = starry.Map(ydeg=3)
    map[1:,:] = yval
    return map.minimize()

yval = np.random.randn(15)

arg1 = tt.dvector()
t_hotspotlon = theano.function([arg1], hotspotlon(arg1))

t_hotspotlon(yval)
```
This crashes with ValueError: expected an ndarray. I think this somehow has to do with the return of map.minimize(), particularly the latitude and longitude. If hotspotlon() only returns the minimum of the map, it seems to work just fine. 

Ideally I would also pass ydeg to hotspotlon() (or better yet, define the map outside the theano function, although it's not clear to me how to do that). But it doesn't seem like theano integers can handle being cast with int() so the call to starry.Map() fails.

**Comment by rodluger** [comment]
Strange. I don't see anything wrong with how you're setting that up. Let me play around with it -- I'll report back soon.

**Comment by rodluger** [comment]
I think I fixed the issue. @rychallener can you pull from master and try again with the same code?

**Comment by rychallener** [comment]
Looks like it's working. Thanks!

**Comment by rodluger** [comment]
Awesome. Thanks for helping me catch that issue.
