### ISSUE TITLE
Numerical integrator needs work

### ISSUE THREAD

**Issue by rodluger** [rodluger/starry#27]
The adaptive mesh technique doesn't converge to the right answer as the requested precision is increased indefinitely. We need stronger ways to ensure the mesh is refined near the occultor boundary.

**Comment by rodluger** [comment]
I've made significant progress on this. Turns out the average of two angles is not that simple to compute, and the modulo function is defined differently in C++ and Python when the first argument is negative.

The numerical integrator now converges as the tolerance is decreased, but some issues remain. For instance:
```
import starry
import numpy as np
import matplotlib.pyplot as pl
m = starry.Map(2)
m[2,0] = 1
b = np.linspace(-4, 4, 100)
pl.plot(b, m.flux(xo=0, yo=b, ro=2, numerical=True, tol=1e-6))
pl.plot(b, m.flux(xo=0, yo=b, ro=2))
pl.show()"
```
![image](https://user-images.githubusercontent.com/9323819/39274208-9be43966-48b7-11e8-89e5-7a75dac47f3f.png)
I need to investigate those spikes, which don't go away as the tolerance is decreased.

**Comment by ericagol** [comment]
How about you just use a cartesian grid on the star?

**Comment by rodluger** [comment]
I fixed it!
![image](https://user-images.githubusercontent.com/9323819/39276621-47c14e4c-48c0-11e8-856f-71a20b305829.png)

**Comment by rodluger** [comment]
The adaptive mesh is a bit faster and a bit more accurate, so I'm going to go with it. It's behaving well in all the cases I've tested so far, so I'm closing this issue.
