### ISSUE TITLE
Import Issue with Starry

### ISSUE THREAD

**Issue by mkplummer** [rodluger/starry#276]
When I import starry, I get the following error:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-10c95ea0e8bb> in <module>
----> 1 import starry
~\Anaconda3\lib\site-packages\starry\__init__.py in <module>
     15 # Import the main interface
     16 from ._config import config
---> 17 from . import kepler, linalg, maps
     18 from .maps import Map
     19 from .kepler import Primary, Secondary, System
~\Anaconda3\lib\site-packages\starry\kepler.py in <module>
      2 from . import config
      3 from ._constants import *
----> 4 from .maps import MapBase, RVBase, ReflectedBase
      5 from ._core import OpsSystem, math
      6 from .compat import evaluator
~\Anaconda3\lib\site-packages\starry\maps.py in <module>
      2 from . import config, legacy
      3 from ._constants import *
----> 4 from ._core import OpsYlm, OpsLD, OpsReflected, OpsRV, math
      5 from ._core.utils import is_theano
      6 from ._indices import integers, get_ylm_inds, get_ul_inds, get_ylmw_inds
~\Anaconda3\lib\site-packages\starry\_core\__init__.py in <module>
      1 # -*- coding: utf-8 -*-
----> 2 from . import core, ops, utils, math
      3 from .core import *
~\Anaconda3\lib\site-packages\starry\_core\core.py in <module>
      2 from .. import config
      3 from .._constants import *
----> 4 from .ops import (
      5     sTOp,
      6     rTReflectedOp,
~\Anaconda3\lib\site-packages\starry\_core\ops\__init__.py in <module>
      1 # -*- coding: utf-8 -*-
      2 from .exceptions import *
----> 3 from .filter import *
      4 from .integration import *
      5 from .limbdark import *
~\Anaconda3\lib\site-packages\starry\_core\ops\filter.py in <module>
     10     STARRY_OREN_NAYAR_DEG = 5
     11 else:
---> 12     from ..._c_ops import STARRY_OREN_NAYAR_DEG
     13 
     14 
ImportError: DLL load failed: The specified module could not be found.
```

**Comment by rodluger** [comment]
Hey @mkplummer can you tell me a bit more about your setup? Looks like you're on windows. How did you install starry and which version is it?

**Comment by mkplummer** [comment]
Thank you! I am running the module via Jupyter Workbook. Looks like Starry 1.1.0 on Python 3.7.3 and Conda 4.9.3 are my current versions.

I appreciate the help!

**Comment by rodluger** [comment]
Thanks. And did you install it via pip or by cloning the repo and running setup.py?
It would also be helpful if you could list the contents of the directory
```
~\Anaconda3\lib\site-packages\starry
```

**Comment by mkplummer** [comment]
Thank you again! I installed via pip. Would it work better the other way (by cloning the repo and running setup.py)?

Here are the contents of my directory:

![image](https://user-images.githubusercontent.com/80552610/112062089-05a9d880-8b25-11eb-8126-422c9f7e92be.png)

**Comment by rodluger** [comment]
@mkplummer The `_c_ops` DLL it's complaining about not being able to find is the compiled C++ code, which I think is the `_c_ops.cp37-win_amd64.pyd` file I see listed there. So it's not immediately obvious to me what's causing the issue.

Can you try cloning the repository and running `python setup.py install`, and letting me know what happens?

If that doesn't work, can you try creating (and activating) a fresh [conda virtual environment](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-with-commands) and trying to pip install inside of that?

**Comment by rodluger** [comment]
@dfm The Windows wheels seem to be ok: https://github.com/rodluger/starry/actions/runs/679686498. Any ideas what the issue might be?

**Comment by dfm** [comment]
There can be issues with wheels and linked libraries on Windows that can result in useless errors like this, but I'm not sure if that's what would be happening here (I don't think there should be any linking required for starry!).

So, @mkplummer: one option would be to try installing from source. I think the following would work:

```bash
pip uninstall starry
pip install -U starry --no-binary starry
```

I can try playing around with this on Windows later if you continue to have trouble.

**Comment by mkplummer** [comment]
Good morning! Thank you for your help. After uninstalling starry, I executed the "pip uninstall -U starrry --no-binary starry" cmd, and here was the results:
![image](https://user-images.githubusercontent.com/80552610/112162925-22402200-8bb2-11eb-99b1-e30dfbbea930.png)
Followed by a string of errors and then,
![image](https://user-images.githubusercontent.com/80552610/112163052-456ad180-8bb2-11eb-808a-131f5822252d.png)
So I believe I need to update my microsoft C++, I will see if this helps. Once again, I really appreciate the help.

**Comment by rodluger** [comment]
Keep us posted!

**Comment by mkplummer** [comment]
I wound up updating Visual C++, Python, and reinstalled starry, theano, exoplanet and matplotlib via conda and python. So far everything seems to be working now. Thank you!

**Comment by rodluger** [comment]
Great, glad to hear. Feel free to re-open the issue if you run into trouble again.
