### ISSUE TITLE
bug in sys.position

### ISSUE THREAD

**Issue by rodluger** [rodluger/starry#285]
Getting
```
TypeError: TensorType does not support iteration. Maybe you are using builtin.sum instead of theano.tensor.sum? (Maybe .max?)
```
when calling ``system.position(t)``. I think one of the ``exoplanet`` methods changed -- should be an easy update.

**Comment by dfm** [comment]
I don't _think_ any of the relevant exoplanet functions have changed recently...

**Comment by rodluger** [comment]
Yeah @dfm you're right -- must have always been broken, just never unit tested! Sorry for the false alarm...
