### ISSUE TITLE
Luminosity units don't make sense

### ISSUE THREAD

**Issue by rodluger** [rodluger/starry#34]
I'm going to ditch the luminosity option in the `Star` object. This way users can just specify the luminosity of the planet relative to that of the star, which will make unit analysis less messy, especially when converting luminosity to flux and factoring in the telescope size and such.

I need to re-think how to compute the total luminosity for a limb-darkened star. I need to treat this case separately since the star isn't *really* described by a 2nd order spherical harmonic expansion; rather, it just **appears** to be from the observer's perspective (for instance, as the star rotates, a dark nightside doesn't come into view!). Note that because of this, the units of the light curve don't make any sense currently!

**Comment by rodluger** [comment]
Stellar radius and luminosity are now fixed to unity. I'm going to tackle the normalization issue next.

**Comment by rodluger** [comment]
Case in point:
```
import matplotlib.pyplot as pl
import starry
import numpy as np

star = starry.Star()
planet = starry.Planet(L=1e-2, r=0.1, a=3)
sys = starry.System([star, planet])
time = np.linspace(0.25, 1.25, 10000)
sys.compute(time)
pl.plot(time, sys.flux / np.nanmedian(sys.flux), label="Uniform")

star[1] = 0.4
star[2] = 0.26
sys.compute(time)
pl.plot(time, sys.flux / np.nanmedian(sys.flux), label="Limb-Darkened")

pl.legend()
pl.show()
```
![image](https://user-images.githubusercontent.com/9323819/39315895-2cdec076-494e-11e8-865a-a267909d7e67.png)

**Comment by rodluger** [comment]
OK, I think I understand what I'm doing wrong. Currently my `Y_{0,0}` coefficient depends on the limb darkening coefficients:
![image](https://user-images.githubusercontent.com/9323819/39321721-33b2ac9a-495e-11e8-8324-d5c9e5298f3a.png)
because that's what I get when I express
![image](https://user-images.githubusercontent.com/9323819/39321793-57b4ec8e-495e-11e8-87f1-c8fdce7a7f10.png)
in spherical harmonics. So I just need to normalize the map so the luminosity doesn't change when the limb darkening coefficients are changed.

But I'm still a bit confused about this, because the stellar brightness isn't *really* a sum of the `Y_{l,0}` harmonics -- it just *looks* that way from our vantage point. If we go around to the backside of the star, we don't see negative flux! So I'm not convinced the limb darkening terms integrate to zero over all 4 * pi steradians. Does that make sense?

**Comment by ericagol** [comment]
Right - there is some sleight-of-hand here, and so it depends on what quantity you are interested in.

If you want the apparent luminosity, then you should integrate the observed flux and multiply by 4\pi d^2.  If you want the total luminosity (i.e. sum of fluxes of observers at same distance distributed over 4\pi steradians), then it's only the monopole that counts.

**Comment by rodluger** [comment]
Ok, let me ask you a specific question then: say I have two solar-type stars with the same total luminosity, but one is strongly limb-darkened and the other isn't. When I integrate the specific intensity of each one over their visible disk, should I get the same value for both? Or should the limb-darkened one be dimmer?

This will help me decide how to normalize the units...

**Comment by ericagol** [comment]
If both stars are isotropic, then by definition they have the same flux for *every* observer.  So, when you integrate the specific intensity over the visible disk (and over wavelength if the bolometric luminosities are equal;  otherwise you require the specific luminosities to be equal), then the fluxes must match.

**Comment by rodluger** [comment]
Ha, turns out I had done this before! From Equation (67) in our PPO paper, all we need to do is multiply the flux by
![image](https://user-images.githubusercontent.com/9323819/39428244-12073a64-4c5d-11e8-984a-f5f55d3bcf3a.png)
to ensure the integral over the visible disk is unity.

**Comment by rodluger** [comment]
Actually the above expression normalizes the flux to `pi`. Anyways, this issue is now resolved. The stellar flux is now always unity.

```
import matplotlib.pyplot as pl
import starry
import numpy as np

star = starry.Star()
planet = starry.Planet(L=1e-2, r=0.1, a=3)
sys = starry.System([star, planet])
time = np.linspace(0.25, 1.25, 10000)
sys.compute(time)
pl.plot(time, sys.flux, label="Uniform")

star[1] = 0.4
star[2] = 0.26
sys.compute(time)
pl.plot(time, sys.flux, label="Limb-Darkened")

pl.legend()
pl.show()
```

![image](https://user-images.githubusercontent.com/9323819/39437047-1b1b3862-4c76-11e8-8e35-ea8b090b010f.png)

**Comment by ericagol** [comment]
This is probably similar to the \Omega parameter in Mandel & Agol for 
the non-linear law.
