### ISSUE TITLE
Comments on the paper:

### ISSUE THREAD

**Issue by ericagol** [rodluger/starry#35]
1).  Are the spherical-harmonic angles \phi & \theta (which appears in section 2.1) different from the \phi and \theta which appear later in the paper (\theta is referenced just after equation 16, while \phi is discussed just after equation 24)?  If so, it might be good to use some distinguishing marker to indicate that these are not the same variable.

2).   Are the coordinates defined just after equation 2 left-handed?  If so, this seems to contradict the description in Figure 1, which is right-handed, with the observer at +\infty.

3).   Is the n subscript in equation (7) the same as the subscript n in equation 5?

4).  In Figure 2, is it true that \phi is negative?

5).  Can the Y_{lm} coefficients be allowed to vary with time?  This might be useful, for instance, for modeling a spotted star with evolving spots.

6). Does first case in D32 require \mu to be even?

**Comment by rodluger** [comment]
Thanks for the comments! I'll push my changes soon:

1. Yes, they're different. Good idea.
2. Good catch. The observer is at $+\infty$ and the coordinate system is in
fact right-handed.
3. Yes. I only ever use $n$ as that specific index, related to $l$ and $m$
via Equation (5).
4. Yes, it's negative. Both $\lambda$ and $\phi$ are measured
counter-clockwise from the $x$ axis.
5. *Yes* and this is a great idea. There's actually negligible speed
overhead when doing this! Also, I was thinking of modeling differential
rotation as the sum of several spherical harmonic maps rotating at
different rates. This could model, eg, a spot near the equator and a spot
near the pole, and the time evolution could cause them to grow and shrink
with time. This probably merits its own paper. What do you think?

**Comment by rodluger** [comment]
Changes made to the manuscript.
