### ISSUE TITLE
Equations (D37) & (D38)

### ISSUE THREAD

**Issue by ericagol** [rodluger/starry#37]
In equation (D37), what conditions hold for p in the second case and q in the third case?

In equation (D38), d_4 simplifies to (3-p)*k^2

**Comment by rodluger** [comment]
Ah, good catch. Fixed.

**Comment by rodluger** [comment]
In (D37), if both p >=4 and q >=4, either of the bottom two expressions can be used. Should I add conditions to make this clearer? I've been treating these piecewise functions as "if" statements, checked in order. As soon as one of them is true, only that expression is evaluated.

**Comment by ericagol** [comment]
I ended up looping over p and then q, so first I used the d3/d4 expression for q=0,2 and then I subsequently used the d1/d2 expression for higher values of q.
