### ISSUE TITLE
Rossiter-McLaughlin effect?

### ISSUE THREAD

**Issue by ericagol** [rodluger/starry#38]
Does STARRY give a means of computing the Rossiter-McLaughlin effect?

The Doppler-shifted surface brightness could be decomposed as spherical harmonics.

**Comment by rodluger** [comment]
Wow, this is a great idea. Shouldn't we be able to model the Doppler shift
exactly with just the l=1 harmonics?

**Comment by rodluger** [comment]
Currently the code doesn't do wavelength dependence but this is a somewhat
trivial addition. I was saving it for v2 -- we already have a lot to work
on for that, so this could be an awesome topic to cover in detail in the
next paper (#3 at this rate!)

**Comment by rodluger** [comment]
I'm currently implementing this for work with @megbedell. Seems to work great, but I should lift the requirement that the `Y_{0,0}` coefficient of `starry.kepler.Primary` instances be fixed at unity. When using `starry` to model the R-M effect, this corresponds to the net radial velocity of the star, which I think we want to be zero. The orbital/systemic motion should be added later, I think.

**Comment by rodluger** [comment]
This is being implemented in the `v2` branch.
