### ISSUE TITLE
Problem computing M_{p,q} and J_{u,v} when b=0 (and solution).

### ISSUE THREAD

**Issue by ericagol** [rodluger/starry#41]
For b=0, k^2 = \infty, so M_{p,q} and J_{u,v} become problematic to compute.

However, for b=0,

J_{u,v} = \int_{\pi-\phi}^{2\pi+\phi} c_\varphi^u s_\varphi^v (1-r^2)^{3/2} d\varphi

= (1-r^2)^{3/2} I_{u,v}

**Comment by rodluger** [comment]
I found this, too :) It's already implemented in starry:
![image](https://user-images.githubusercontent.com/9323819/39274304-e7c58600-48b7-11e8-837f-1b8bb724db78.png)
