### ISSUE TITLE
NaNs when b = r > 1 for s2 term

### ISSUE THREAD

**Issue by rodluger** [rodluger/starry#45]
```
>>>import starry
>>>m = starry.Map()
>>>m[1, 0] = 1
>>>m.flux(yo=2, ro=2)
nan
```

**Comment by rodluger** [comment]
It's due to [this line](https://github.com/rodluger/starry/blob/e67a4b88bb501010b7b53f1587c163546303f34e/starry/taylor.h#L32) in the computation of the Pi elliptic integral for the Taylor-expanded version of `s2`. I'm going to try to Taylor expand this -- the elliptic integral is zero in the limit, but the numerical computation blows up.

**Comment by rodluger** [comment]
I found a good expansion. It's almost certainly overkill -- we can cut several of the higher order terms for speed.
![image](https://user-images.githubusercontent.com/9323819/39397594-3132e04a-4ad8-11e8-81bb-c55aa40fd224.png)

**Comment by rodluger** [comment]
Well that didn't work! [This line](https://github.com/rodluger/starry/blob/e67a4b88bb501010b7b53f1587c163546303f34e/starry/taylor.h#L39) also needs to be fixed. Shouldn't be too hard...

**Comment by rodluger** [comment]
Fixed! This expression is extremely stable and diverges only when |b - r| is on the order of 1e-12. So a linear expansion did the trick!

**Comment by ericagol** [comment]
Okay, great!  There may also be a transformation that works as well.
