### ISSUE TITLE
Instabilities!

### ISSUE THREAD

**Issue by rodluger** [rodluger/starry#47]
@ericagol: I created a [branch](https://github.com/rodluger/starry/tree/master-stability) to keep track of the instabilities in the code. Whenever anyone commits changes, add `[stability]` somewhere to the commit message to automatically generate the diagnostic plots on **travis**. These will be force-pushed to the `master-stability` branch (or `whatever-stability`, where `whatever` is the current branch name).

The plots are generated for every spherical harmonic, currently up to 4th order. They are plots in the `b-r` plane of the fractional and relative error compared to calculations done using 128-bit precision. The subplots below the main plots are zoomed-in regions about the usual suspects: `b = r`, `b = r - 1` and `b = r + 1`. 

The attached plot is for the `Y_{1,0}` spherical harmonic (the `s2` linear limb darkening term). As you can see, we've managed to fix most of the instabilities except

- `b = r` for `0.5 < r < 2`. That's described in [this issue](https://github.com/rodluger/starry/issues/46).
- `b = r - 1` for `r > 1`. This corresponds to the infinitesimal time before totality, where only a tiny sliver of the body is visible and the total flux is very close to zero. Since the relative error is small (see right panel), I'm not worried about this instability. We shouldn't really care if our calculations give 1e-10 when the true flux is 2e-10, for instance. That's a large (100%) fractional error, but completely unmeasurable.

![image](https://user-images.githubusercontent.com/9323819/39426641-00b7a39e-4c57-11e8-812b-7637c398c1d2.png)

**Comment by ericagol** [comment]
Nice!  We should also examine the regions near b = 1-r,  b=0, r=0, and b=r=0.

**Comment by ericagol** [comment]
What is the difference between \Delta and \epsilon?

**Comment by rodluger** [comment]
Ah, Delta is 0.1 and epsilon is 1e-6
