### ISSUE TITLE
Gradient of elliptic Pi

### ISSUE THREAD

**Issue by rodluger** [rodluger/starry#48]
@dfm Can you help me wrap my head around the gradient of the elliptic integral Pi on [this line](https://github.com/rodluger/starry/blob/72a8bea59d9cd8461c1626bd9400b73d832b1031/starry/ellip.h#L118)? The integral is a function of two parameters, so shouldn't there be two derivatives? This function currently only returns one -- which appears to be the sum of each of the derivatives. What's going on there?

**Comment by dfm** [comment]
`n.derivatives()` and and `ksq.derivatives()` are both *vectors* and the gradient of Pi will also be a vector. Try working through what happens if `n.derivatives() == (1, 0)` and `ksq.derivatives() == (0, 1)`...

**Comment by rodluger** [comment]
Got it. Thanks!
