### ISSUE TITLE
Flux integration

### ISSUE THREAD

**Issue by rodluger** [rodluger/starry#54]
I still need to code up an exposure time option to numerically integrate the light curve over the exposure window.

**Comment by dfm** [comment]
My method looks like this: https://github.com/dfm/transit/blob/master/transit/include/integrator.h#L24-L52

It a recursive method where you look at the difference between the linear prediction for the midpoint and the actual value and recursively refine until the difference is small.

I use autodiff on this and it seems to work fine!

**Comment by dfm** [comment]
Yeah - the actual defaults I use are `tol=1e-8, maxdepth=4` but you'll want to play around with that.

**Comment by ericagol** [comment]
@dfm @rodluger When you set the tolerance, do you scale it with, say, the radius-ratio squared so that the precision scales with the depth of transit?  Or do you keep it a constant?

**Comment by rodluger** [comment]
@ericagol I don't scale it; it's just a knob the user can set. I'm finding that in order to get sub-ppm precision I need to recurse many dozens of times, which is pretty unfortunate. We should try to come up with a faster way of doing this. I still want to try out my idea of computing the fluence integral analytically...

**Comment by rodluger** [comment]
Perhaps since we can so easily compute dF/dt we could do a Taylor expansion of the fluence. But I think @dfm once scoffed at that idea :)

**Comment by ericagol** [comment]
@rodluger I'm not sure that I follow...

**Comment by rodluger** [comment]
@ericagol We want to take the time integral of F over the exposure window. I'm suggesting we expand F as F0 + dF/dt * delta t, whose integral is trivial if we assume dF/dt is constant. Alternatively, we could take higher order derivatives (which we could probably compute analytically) to get higher precision.

**Comment by dfm** [comment]
I "scoff" at a lot of things ... don't take it too seriously ;-)

**Comment by ericagol** [comment]
@rodluger That's a good idea, but I think it simply amounts to a higher-order integrator.

**Comment by rodluger** [comment]
@ericagol I like that idea a lot.

**Comment by ericagol** [comment]
@rodluger Another thing I'm thinking about:  the points of contact are smoothly varying for all `Y_{lm}` beyond `l=m=0`.  So, I suspect that the numerical time integration needs to be finest for just the uniform component.  If we make the approximation that the velocity is constant over the integration time, then *I think* we can compute this analytically in terms of incomplete elliptic integrals.  In which case the numerical integration could be carried out for all the fluxes beyond the uniform term, while the uniform case could be computed separately analytically.

**Comment by rodluger** [comment]
@ericagol @dfm I'm going to play around with these different integration methods. I think this could even be its own paper. If my idea of Taylor expanding the integrand pans out, here's what the fluence integral will look like:
![image](https://user-images.githubusercontent.com/9323819/46873873-b7496900-ce05-11e8-97a8-acc9ec8f128d.png)
where `eps` is the exposure time and `t0` is the bin center. Interestingly, all the odd-order derivatives cancel out, so we'll only need the even-order derivatives `dF/db`. I can probably differentiate the `dF/db` expression in the paper once by hand, but we might want to use autodiff for higher order derivs.

**Comment by rodluger** [comment]
I also suspect that this series converges very quickly. Assuming the number of operations is about the same for each derivative order (if we're able to get analytic expressions for them, and recycle a lot of terms), I suspect this will be much faster than calling the flux function tens of times to approximate the fluence.

**Comment by rodluger** [comment]
@ericagol @dfm Quick update on this. Here's an example of what I'm thinking of doing:
![image](https://user-images.githubusercontent.com/9323819/47670017-97929e80-db82-11e8-95f4-76d106970754.png)
The top panel shows the flux (blue) and the fluence computed with extremely high precision Gaussian quadrature (black). Overlaid on the black line are my approximations using second derivatives *only*. The bottom panel shows the relative error for increasing numbers of second derivative evaluations. Basically we can get sub-ppm precision by subdividing the exposure window into ~4-8 bins and computing the flux and its second derivative once in each bin. This *should* be significantly faster and more precise than methods that rely only on the *value* of the flux, especially since if we have analytic expressions for the second derivative they should be cheap to compute, as they depend on the same terms as the flux.

@ericagol How hard would it be for you to compute the second derivative of the flux with respect to `b`? (And do you think you'll have time in the near future?) I'm happy to do it, but you're definitely better at it than I am. DFM and I are thinking of writing a separate paper/letter on this method, but there's no particular rush.

**Comment by ericagol** [comment]
@rodluger    That looks impressive!  The second derivatives are not well defined across the points of contact - do you identify each contact point first, and then bin between the contact point and the boundary of the time bin which straddles it?

I have only computed the derivatives analytically for the `m=0` case (for the limblark code).  Of course, if you want to continue computing the derivative of the time-integrated light curve, then you would need the third derivative as well.  These may not be too difficult to compute - I'm happy to look into this, but not sure when I will have time.

**Comment by rodluger** [comment]
@ericagol Yes, I identify all the necessary subdivisions to ensure the derivatives are well-behaved in the limits of integration. But this is still for an occultor moving along the x axis at constant speed, so I'm going to have to work out the math for identifying the times of contact for arbitrary occultor paths. I'm still not sure how to do it, but a constant velocity (or constant acceleration) approximation will probably be good enough.

As for the analytic derivatives, yes, the `m=0` is all I need. I suspect the non-radial terms are really hard! And as for derivatives of the time-integrated model, I'd probably just use autodiff.

**Comment by rodluger** [comment]
Migrated to #186.
