### ISSUE TITLE
r >= 1 and b=0 might cause an error in this line

### ISSUE THREAD

**Issue by ericagol** [rodluger/starry#55]
If r >=1 and b=0, the source is completely occulted, so perhaps s2 isn't called.  But, s2 is called with b=0 and r >=1, this line may cause a problem:

https://github.com/rodluger/starry/blob/9476c4c25f23c3798d260d8b77c7f911b2cf8fb1/starry/lld.h#L189

**Comment by rodluger** [comment]
That line never runs because (as you suspected) `s2` is only called when there's an occultation.

**Comment by ericagol** [comment]
It might be worth returning zero immediately if b <= 1+r just in case someone tries to call it in the fully occulted case.
