### ISSUE TITLE
Gradients broken when integrating flux over exposure time

### ISSUE THREAD

**Issue by rodluger** [rodluger/starry#56]
I'm probably doing something dumb. These gradients don't look right (and there are small instabilities popping up in places):
![image](https://user-images.githubusercontent.com/9323819/40151625-11262f48-5936-11e8-84c4-71d813d69ce4.png)

**Comment by ericagol** [comment]
I think the gradients look fine - do they agree with the finite difference derivatives computed at high-precision?

It's strange that the instabilities show up away from the contact points.

Can you share the values of b, r, u1 & u2 that you used?  And also the values of ARy as a function of time?

**Comment by rodluger** [comment]
The gradients are shifted incorrectly to the left; look at the time derivative (first line) -- it's zero during most of egress, which is wrong. When the exposure time is zero, I get the correct result. I generated this plot using [this](https://github.com/rodluger/starry/blob/832585794b50f0864c6ab674b20366a5caab337d/tex/figures/autodiff.py) script. The planet/star params are on lines 18-24.

**Comment by rodluger** [comment]
@dfm might have some suggestions. Relevant lines in the code are [here](https://github.com/rodluger/starry/blob/b912ddcf0c222746f8718d303e88e36a6662f970/starry/orbital.h#L455-L479), [here](https://github.com/rodluger/starry/blob/b912ddcf0c222746f8718d303e88e36a6662f970/starry/orbital.h#L481-L520), and [here](https://github.com/rodluger/starry/blob/b912ddcf0c222746f8718d303e88e36a6662f970/starry/orbital.h#L693).

**Comment by rodluger** [comment]
Never mind, I figured it out -- I wasn't properly summing the fluxes of the individual bodies at each time step. Don't bother trying to reproduce this issue -- it's specific to how I coded things up. Will resolve it shortly.
