### ISSUE TITLE
Add option to account for light travel time

### ISSUE THREAD

**Issue by rodluger** [rodluger/starry#66]
Spiderman does it -- it shouldn't be too hard to implement.
https://github.com/tomlouden/SPIDERMAN/blob/7d328dc93889c1229fdaa3076b98493a4ef5cd09/c_src/web.c#L123-L137

**Comment by rodluger** [comment]
We need to be careful if we're going to also model planet-planey occultations with this -- the timing offset of the events could get tricky?

**Comment by rodluger** [comment]
@ericagol I think I got this working. This [script](https://github.com/rodluger/starry/blob/d279aba5e2249db19f682067a466c6d15a4b9676/misc/delay.py) plots the light curve for a hot Jupiter with a dipole map for different semi-major axes at a fixed period of 1 day (the values are greatly exaggerated so we can see the shift by eye):
![image](https://user-images.githubusercontent.com/9323819/40435312-406a76e0-5e65-11e8-84e7-08e75e4bf3c7.png)
How should we go about checking my code? Can you compute the expected time of secondary eclipse for each of the cases in the figure and let me know what you get? Here's what I have:

```
a [AU]        t_sec [days]
===========   ==================
0.0           0.5
0.232456517   0.5027
1.162282585   0.51337
2.32456517    0.52643
```

(The case where a=0 is obviously unphysical, but it mimics a system with zero light travel time delay).

**Comment by ericagol** [comment]
If orbit is circular and edge-on, delay should be 2a/c.

I find offsets of:
0, 0.0214, -0.08, -0.6
of the data in that table from 2a/c.

Is there some inclination?
![time_delay](https://user-images.githubusercontent.com/243664/40439755-c85af218-5e70-11e8-9c7d-c332faa96258.png)

**Comment by rodluger** [comment]
@ericagol Hmm. No inclination, zero eccentricity. I see the discrepancy as well when I compute `2 * a / c`. Here's what I'm doing:

- Compute the z coordinate of the point closest to the observer, `z0`. In our case, with the z axis pointed at the observer, `z0 = a`. This is my reference point for computing the retarded position of the planet.
- Compute the time delay, `dt = (z0 - z) / c`, where `z` is the true instantaneous position of the planet. At true opposition, `z = -a`, so the time delay agrees with your formula.
- Compute the retarded position, `x' = x - dt * vx`, where `x` is the true instantaneous position on the sky and `vx` is the true instantaneous velocity.
- Compute and log the phase when `x'` = 0`.

I think the disagreement comes from the fact that `vx` is changing and my formula only applies in the limit that it is constant. I couldn't figure out a way to account for the acceleration without doing something recursive, but perhaps there's a more intelligent way?

**Comment by ericagol** [comment]
Does the planet have mass?

If so, that modified the formula since the time offset is relative to the barycenter.

If the planet were as massive as the star, then there is no time offset.

Eric Agol
Astronomy Professor
University of Washington

**Comment by ericagol** [comment]
Also the outer planet is moving 4000 km/sec, which is a bit high for this test.

**Comment by rodluger** [comment]
Agreed -- this is all very unphysical. I definitely assumed v/c << 1 in my derivations. Do you think I have a bug still?

**Comment by ericagol** [comment]
I'm not sure... the dt = 2*a/c estimate assumes a massless planet, and it ignores the retarded time.  If you turn off the retarded time, do you match the 2a/c delay?

**Comment by rodluger** [comment]
Well, yes. The time delay at opposition is exactly `dt = 2a/c`. But that's not something I can use directly, as I need to compute what the light curve looks like at time `t` (the time requested by the user), not at time `t + dt`. I think the way to do this correctly would be iterative: figure out where the planet was at `t - dt`, re-compute `dt`, re-compute the position, and so forth, until convergence. Does that make sense?

**Comment by ericagol** [comment]
Yes, I think it may have to be iterative.  That's good that it agrees at opposition - it could be that your code is giving the correct answer;  I was not correcting for the motion of the planet.

**Comment by rodluger** [comment]
Here's the equation I think we want to solve:
![image](https://user-images.githubusercontent.com/9323819/40458568-6950a286-5eb1-11e8-964c-55aaf1d62a11.png)
That is, the observed position at time `t + dt` equals the true position at time `t`. We can re-write this in terms of `x'(t)`, which is what we actually care about:
![image](https://user-images.githubusercontent.com/9323819/40458602-ac757910-5eb1-11e8-87f9-184be9c47bfd.png)
The expression on the right hand side is transcendental. I suggested Taylor expanding it:
![image](https://user-images.githubusercontent.com/9323819/40458794-c340c40a-5eb2-11e8-9b61-29aaa2c33e42.png)
So, if we compute `dt` from the body's true position at time `t`, as well as its velocity and acceleration, we have simply
![image](https://user-images.githubusercontent.com/9323819/40458694-3bb0636a-5eb2-11e8-85f6-89090d7254fb.png)
@ericagol Does this look OK? The correction term due to the acceleration should make us agree better.

**Comment by rodluger** [comment]
I'm going to keep this open since I still need to test this for eccentric, inclined orbits.

**Comment by rodluger** [comment]
I've tested this on eccentric and inclined orbits and it works!

**Comment by rodluger** [comment]
For what it's worth, I found a thinko in my math. The time delay should be computed based on the *retarded* position, not the actual position, since that is where the photon left from! The math gets trickier, but since we're only expanding stuff to 2nd order, it boils down to solving a quadratic equation for `dt(x'(t))`. Here's the derivation, if we ever choose to revisit this.
![img_20180530_154100](https://user-images.githubusercontent.com/9323819/40752282-ab79e2fe-6423-11e8-9767-8aef588dda81.jpg)
