### ISSUE TITLE
Pre-compiled binaries on PyPI

### ISSUE THREAD

**Issue by rodluger** [rodluger/starry#73]
@dfm Do you know how to do this? Compiling takes ~2 minutes, and it would be nice if most users didn't have to sit through that when pip installing the package.

**Comment by dfm** [comment]
I'd recommend making a conda-forge package. That'll be a lot easier because you won't need to support building all the binaries yourself!

**Comment by dfm** [comment]
e.g.: https://github.com/conda-forge/celerite-feedstock

**Comment by rodluger** [comment]
Cool, I'll play around with that. Thanks!

**Comment by dfm** [comment]
I'm also happy to write up the recipe if you don't want to. Just let me know!

**Comment by dfm** [comment]
cool. Just ping me when you want me to have a go.

**Comment by rodluger** [comment]
@dfm What about Windows builds? I've seen you do stuff with Appveyor -- I'm assuming Travis doesn't support Windows. How hard is it to get CI working for starry on Windows machines?

**Comment by dfm** [comment]
I'm trying to set this up, but you might need to log into appveyor and enable it for this repo...

**Comment by rodluger** [comment]
Done!

**Comment by dfm** [comment]
So. Building on Windows is proving to be difficult. The logs are here: https://ci.appveyor.com/project/dfm/starry-owxbn

There are about infinity compiler warnings (mostly/all warning #4503) but the internet suggests that maybe we can ignore that. Then the tests crash without any error message (`Command exited with code -1073740791`). I'm not entirely sure what to try or how to track down this problem...

**Comment by rodluger** [comment]
So weird. You could try the `-s` command [when invoking pytest](https://github.com/dfm/starry/blob/windows/appveyor.yml#L30) to disable stdout/stderr capture and see if it spits out anything useful...

**Comment by rodluger** [comment]
@dfm Any updates on this?

**Comment by dfm** [comment]
I don't. I tried the `-s` command but it doesn't catch anything because it's just a segfault and it seems to happen as soon as we instantiate any of the starry classes...

I don't have access to a Windows machine or any expertise here so I'm inclined to just skip windows for now. If someone needs it, perhaps they can help us make it work :-)

**Comment by rodluger** [comment]
@dfm Ok, sounds good! I'll ping you about conda-forge at some point -- I think we're approaching a stable version of the code.

**Comment by rodluger** [comment]
Discussion continued in #136.
