### ISSUE TITLE
Evaluating large `l` spherical harmonics

### ISSUE THREAD

**Issue by ericagol** [rodluger/starry#81]
The factorials in equations (A3) (`A_{lm}`), (A6) (`B_{lm}^{jk}`), and (A8) (`C_{pq}^k`) can be computed using the [`log \Gamma` function](http://mathworld.wolfram.com/LogGammaFunction.html).

I suspect that this should help in preventing overflow/underflow problems when `l` is large.

**Comment by rodluger** [comment]
We could also use the gamma ratio function (#98) or compute the coefficients using multi-precision and cast to double (this is done **once** when the map is instantiated, so the overhead would be small.)

**Comment by rodluger** [comment]
I spoke with Keaton Burns and he said that people usually compute the spherical harmonics from Legendre polynomial recursion relations, which are extremely stable up to `l` of several *thousand*. I will try to code this up for the next version of `starry`.

**Comment by ericagol** [comment]
Great!  Was that Keaton Bell?

**Comment by rodluger** [comment]
No -- [Keaton Burns](http://keaton-burns.com/); he does fluid dynamics here at the CCA and uses spectral methods & spherical harmonics to solve his ODEs.

**Comment by rodluger** [comment]
Migrated to #186.
