### ISSUE TITLE
A simplification for r+b < 1, k^2 > 1:

### ISSUE THREAD

**Issue by ericagol** [rodluger/starry#83]
I think that in this case the `\mu/2` even case simplifies to a sum over polynomials and factorials:

![image](https://user-images.githubusercontent.com/243664/41183966-32d91642-6b32-11e8-8e2a-18a5c8fa4d1c.jpeg)

where `A_{i,u,v}` is a polynomial in `\delta` which is the same as that defined in appendix D.2.3.

`{\cal P}({\bf G}_n) &= 2\pi(2r)^{l+2} \sum_{i=0}^{\mu/4+\nu/2}A_{i,\tfrac{\mu}{4},\tfrac{\nu}{2}} \frac{(2i+\tfrac{\mu}{2}+1)!!}{2^{\tfrac{\mu}{4}+i}(\tfrac{\mu}{4}+i+1)!}`

**Comment by rodluger** [comment]
That makes sense. My expression for `I_{u,v}` involves sines and cosines of
`phi`, but `sin phi` is a simple function of `b` and `r`, so I'm never
doing any trig.

**Comment by ericagol** [comment]
I tried applying the `(1-x)^u (x+x0)^v` expansion to the `P(G_n)` equations in section D.2.1;  however, the `\cos{\varphi}^2` terms need to be expressed as `(1-x^2)^u`, and so I found that I would need to find the expansion as `(1-x)^u (1+x)^u (x+x0)^v` with `x=\sin{\varphi}`.  This is more complicated to work out.  So, instead I just used the same transformation as for the large `r` case in section D.2.3, and that's how I arrived at the above equation.  I also have an equation for the `(\mu-1)/2` even case.

**Comment by ericagol** [comment]
I haven't coded this up yet, but hopefully it will take less time than the `k^2 < 1` case!

**Comment by ericagol** [comment]
I think this equation has a couple of errors still...

**Comment by ericagol** [comment]
I've just corrected the equation above.
