### ISSUE TITLE
Re-parametrization of the formulae for large occultors

### ISSUE THREAD

**Issue by rodluger** [rodluger/starry#84]
Continuation of the discussion in #23.

**Comment by ericagol** [comment]
Okay, I've finally got code working and debugged, and checked the equations in the appendix section D.2.3;  I think these are all correct now for the `b+r>1` and `k^2<1` limit.  I coded this up in the `julia/` directory as `sn_bigr.jl` with an example test `test_sn_bigr.jl`.  It seems to work to ~machine precision for the `r=100` example in that test.

**Comment by rodluger** [comment]
@ericagol Preliminary speed tests look good. For small occultors, your formulae take about twice as long to evaluate as mine, which I think is fine since the extra precision is certainly worth it. But I suspect I can make the code faster in places, so I'm going to keep trying.

As for stability tests, everything improved **dramatically** at all values of `b`, `r`, and `l`! The relative error is less than 1e-13 in nearly all regions of parameter space and does not increase with `l`. One place where I'm finding large relative errors is for `r = 1`, but they are still sub-ppb.

Fractional errors get large and can be > 1 when the flux is below 1e-16, but I suspect this might be hard to fix. 

The most interesting thing is that in the `r = 100` plot below, the `s2` term has the highest error, and that seems to increase without bounds as `r` increases. This is using your `cel` parametrization -- can you check if your Julia version is similarly unstable near ingress and egress?

![image](https://user-images.githubusercontent.com/9323819/41319930-6c317eac-6e52-11e8-9936-c40e2a616115.png)

![image](https://user-images.githubusercontent.com/9323819/41319915-5ff54592-6e52-11e8-8a57-3e6083bb2379.png)

**Comment by ericagol** [comment]
> The most interesting thing is that in the |r = 100| plot below, the 
> |s2| term has the highest error, and that seems to increase without 
> bounds as |r| increases. This is using your |cel| parametrization -- 
> can you check if your Julia version is similarly unstable near ingress 
> and egress?
Yes, I find this as well.  However, this is right at the end of ingress/
beginning of egress when the flux approaches zero.   In this case,
I think the relevant comparison is to the total flux, which is the
relative case.  In this case I find a precision of better than 2e-14,
while in your case the relative precision seems to approach 1e-9?

**Comment by rodluger** [comment]
@ericagol We should make explicit in the text that when `b = 0`, `J_v = I_v`, since our regular expressions blow up at that point. We should probably also re-parametrize to remove the `k^3` from our definition of `L` (D51 and D52), since that term is always multiplied by `F`, which cancels the `(4br)^1.5` in the denominator. This term blows up as `b --> 0`. I see you [coded this up correctly](https://github.com/rodluger/starry/blob/master/julia/sn_bigr.jl#L420) to avoid this, but we should make the text reflect that.

**Comment by ericagol** [comment]
Yes, good points.  I coded it up correctly as well, but didn't change the text to reflect that.

I think you can summarize the above plots by using the asinh error with a transition at, say, `10^{-14}`.

**Comment by rodluger** [comment]
@ericagol Can you write out an expression for how to compute the `asinh` errors? I understand their application to computing absolute magnitudes, since `lim(b --> 0) asinh(0.5/b * f / f0) + ln(b) = ln(f / f0)`, but how exactly do I use this to compute a weighted error from the relative and fractional errors? Thanks!

**Comment by ericagol** [comment]
@rodluger Now that I've thought about this more, I'm not sure it will work.  The idea I was thinking of was that `asinh(x)` approaches `log(2x)` for `x >> 1`, and approaches `x` for `x <<1` (with `b=0`).  So, given some transition point at, say, `x_0=10^{-14}`, for values smaller than this, compute `dx = \sinh^{-1}(x_1/x_0) - \sinh^{-1} (x_2/x_0)`, which for large `x_1/x_0` and `x_2/x_0` will give `dx ~ \log{2x_1/x_0}-\log{2x_2/x_0} = \log{x_1/x_2} ~ x_1/x_2-1` for `x_1 ~ x_2`, which is the fractional error, while for small `x_1` this will become `(x_1-x_2)/x_0`.  I guess I hadn't thought this through carefully enough since I was applying it to a case with `x_0 =1` since I wanted relative errors for `x_1 >> 1` and absolute errors for `x_1 << 1`.

![asinh_vs_log_vs_x](https://user-images.githubusercontent.com/243664/41428420-ec2225c2-6fbe-11e8-97da-99f39cd968ea.png)

**Comment by rodluger** [comment]
@ericagol Hmm, so what are you thinking we should do? Report both fractional and relative errors? Just relative errors?

**Comment by ericagol** [comment]
I think just relative is fine, assuming that we normalize the unocculted flux for each `s_n` to unity.  I think what is going on in the `s_2` case is that the flux of the body goes to zero at the limb, so when the limb peaks out from behind the occulter, there is very little flux that appears at first.  We could try to improve the relative precision, but I don't think it will accomplish much.

**Comment by rodluger** [comment]
Ok, but I think the unocculted flux from most of the `s_n` terms is zero. What should we do in that case?

**Comment by ericagol** [comment]
Oh, good point.  Perhaps normalize by the largest flux that occurs during the ingress/egress?

**Comment by rodluger** [comment]
That's a good idea, and easy to implement! I'll work on that.

**Comment by rodluger** [comment]
Done!

**Comment by rodluger** [comment]
![image](https://user-images.githubusercontent.com/9323819/41481136-aff5b04c-7085-11e8-9d29-66d56b21f337.png)
![image](https://user-images.githubusercontent.com/9323819/41481139-b526a2ec-7085-11e8-8937-591bec499a6f.png)
