### ISSUE TITLE
Some other questions:

### ISSUE THREAD

**Issue by ericagol** [rodluger/starry#88]
- [x]  Do we need an expression near b=0?  k^2 -> \infty, which shows up outside of elliptic integrals. 
- [x] Code just in starry:  paper focuses on spherical harmonics & math.  Can compute arbitrary order limb darkening, but only need m=0 terms.
- [x]  limbdark: rewriting Mandel & Agol linear term with stable formula.  Write down m=0 relations.
- [x]  Compare double-precision versions of Julia & python codes.
- [ ]  Do we need handle special cases separately for n != 2 s_n?  b+r = 1; b=r (or in vicinity)?

**Comment by rodluger** [comment]
@ericagol 
When `b = 0`, `k^2 = infty`, so my recursion formula for `J_{u,v}` doesn't work. The stable expression I derived near `b = 0` comes from Taylor expanding the term in parentheses in the integrand of
![image](https://user-images.githubusercontent.com/9323819/41128056-e0074108-6a61-11e8-822b-f89783d162f9.png)
in terms of `b`. Each term in the series is then a constant times some power of `s`, so the integral can easily be written in terms of `I_{u,v}`. [Here's a sketch](https://github.com/rodluger/starry/raw/master/tex/notebooks/taylorb.pdf) of how I do this in Mathematica.

It would be nice to compute a general expression for the nth term in the series so I don't have to hard-code the coefficients. Mathematica returns a `DifferenceRoot` function that I don't quite understand.

Can you come up with an easy way to Taylor expand `(1 - r^2 - b^2 - 2 b r s)^{3/2}` about `b = 0`?

**Comment by ericagol** [comment]
I'll think about it...   this is going to be problematic when `r ~ 1` since then the portion of the star near `y=-1` will be unocculted.

**Comment by ericagol** [comment]
I think the solution is to use my transformed equations (as I did in section D.2.3 for `k^2 <1`).  See issue #83 - the primitive integral is just a polynomial in `\delta = (b-r)/(2r)` for the `\mu/2` even case, which should be stable to evaluate for small `\delta`.  For the `(\mu-1)/2` even case, I get the following expression:

![image](https://user-images.githubusercontent.com/243664/41131475-d754b55e-6a70-11e8-91fa-31f5b493c57c.jpeg)

It's clear from the form of this expression that it should be stable as `k^2 -> \infty`.  You can either expand the `(1-u/k^2)^{3/2}` term as a series expansion in `k^2`, and do upward or downward iteration, whichever is stable.  This approach should actually work for all `k^2 >1`.

`\mathcal{P}(\mathbf{G}_n) = 2(2r)^{l-1}(1-(b-r)^2)^{3/2} \sum_{i=0}^{\tfrac{l-1}{2}}\mathcal{A}_{i,\tfrac{\mu-1}{4},\tfrac{\nu-1}{4}} \int_0^1 \frac{u^{i+\tfrac{\mu-1}{4}} \left(1+\frac{u}{k^2}\right)^{3/2}}{u^{1/2}(1-u)^{1/2}}`

**Comment by ericagol** [comment]
The only difference in this case is that `J_v` is evaluated from `-\pi/2` to `\pi/2` rather than `-\kappa/2` to `\kappa/2`.

**Comment by rodluger** [comment]
Cool!

**Comment by rodluger** [comment]
I get this for the expansion of J near `k2 -> infty`:
![image](https://user-images.githubusercontent.com/9323819/41168190-0add3fd4-6afa-11e8-89f3-d300d63bef77.png)

**Comment by rodluger** [comment]
@ericagol Ok, I implemented this for all cases and it works great! Right now, I have a constant small threshold for `b` below which I use the Taylor expansion. But I'm finding that the instability occurs at higher values of `b` as `l` increases. It looks like around `l = 15` the instability becomes significant for `b < 0.1`. Your formula, on the other hand, seems to be stable at all `l`. We're going to need to do some more rigorous tests to check when we should switch between the two.

**Comment by ericagol** [comment]
@rodluger  Great!  Or perhaps just use the new formula everywhere?

**Comment by ericagol** [comment]
@rodluger  I've added these fairly hastily;  I have yet to code them up to check for mistakes.  I also added in the `I_0`, `J_0`, and `J_1` terms for upward iteration (in both cases).

**Comment by rodluger** [comment]
@ericagol 
I coded up the `ksq < 1` case and it seems to work great! Here's the stability plot for the Earth's secondary eclipse using your downward recursion (left) and my old approach (right):
![image](https://user-images.githubusercontent.com/9323819/41197979-febd5c92-6c21-11e8-9b6d-0fa12b307a84.png)
Your approach gives 3 orders of magnitude better precision. It's still not at the machine limit -- not sure why, but it could be because the actual flux calculation involves sums and differences of the terms in `s`. Even if `s` is computed to machine precision, the downstream operations can still cause small errors.

**Comment by ericagol** [comment]
Just to the document, although I’m starting to add to code.  I haven’t checked for accuracy yet.

**Comment by ericagol** [comment]
One thing I found that makes a big difference is being careful in computing k_c - you can see how I did it in the code.  Could it also be that some precision is lost in the computation of Y_lm or the rotation matrices?

**Comment by ericagol** [comment]
I've coded up the equations for `k^2 >1` (these are still in the julia code file `sn_bigr.jl`), which seems to work well, even near `b=0`!  However, there are still significant errors for large `l` when `b` is near 0.  I'm wondering whether this may be due to the computation of `H_uv`, for which I'm still using your old formalism.

**Comment by ericagol** [comment]
It turns out that the math for `Q(G_n)` is pretty similar to the `\mu/2` even case for `P(G_n)`.  For `Q(G_n)` I find the expression:

![image](https://user-images.githubusercontent.com/243664/41198907-e675f506-6c3d-11e8-9c1d-cc88ce8fd987.jpeg)

where `A_{i,u,v}` needs to be evaluated at `\delta = -1/2` and `I_v` needs to be evaluated with `\beta` instead of `\kappa`, or equivalently at `k^2=((b+1)^2-r^2)/(4b)` for `r+b > 1`, and for `r+b < 1`, `\beta = \pi/2`.  It's interesting that for this integral the quantity '((b+1)^-r^2)/(4b)` plays the role of `k^2`, and both quantities are `>1` for `b+r <1` and are less than one for `b+r >1`...

`\mathcal{Q}(\mathbf{G}_n) &= 2^{l+3}\int_{-\beta/2}^{\beta/2} s_\varphi^{\tfrac{\mu}{2}+2} (1-s_\varphi^2)^{\tfrac{\mu}{4}+1}(s_\varphi^2-1/2)^{\nu/2} d\varphi\\
&= 2^{l+3} \sum_{i=0}^{\tfrac{\mu}{4}+\tfrac{\nu}{2}+1} \mathcal{A}_{i,\tfrac{\mu}{4}+1,\tfrac{\nu}{2}} \int_{-\beta/2}^{\beta/2} (s_\varphi^2)^{i+\tfrac{\mu}{4}+1} d\varphi\\
&= 2^{l+3} \sum_{i=0}^{\tfrac{\mu}{4}+\tfrac{\nu}{2}+1} \mathcal{A}_{i,\tfrac{\mu}{4}+1,\tfrac{\nu}{2}} I_{i+\tfrac{\mu}{4}+1}\\
\beta/2 &= \sin^{-1} \sqrt{\frac{(b+1)^2-r^2}{4b}}`

**Comment by ericagol** [comment]
@rodluger I just noticed that `H_uv` is zero for odd values of `v`.  So, we can add the extra condition that `\nu/2` must be even, in addition to `\mu/2` when computing `H_uv`.

**Comment by rodluger** [comment]
@ericagol Here's Earth with `lmax=20`: no signs of instabilities!
![image](https://user-images.githubusercontent.com/9323819/41203559-a5457e94-6c8d-11e8-8d96-2ddd479cc79c.png)

**Comment by rodluger** [comment]
@ericagol I think `H_{u,v} = 0` for odd `v` only when the occultor isn't touching the limb, right?

**Comment by ericagol** [comment]
@rodluger  Oh, you are right;  that was the case I was testing.

**Comment by rodluger** [comment]
@ericagol 
Your math for Q(G_n) checks out, but only if I use
![image](https://user-images.githubusercontent.com/9323819/41204608-b33b2a9a-6c9b-11e8-9f4d-95ec7ed2bc09.png)
instead of the value you mentioned.

![image](https://user-images.githubusercontent.com/9323819/41204655-27777b3e-6c9c-11e8-83fa-1078da313df7.png)

**Comment by rodluger** [comment]
I think it may be because you identified `beta/2` with `kappa` instead of `kappa/2`...

**Comment by rodluger** [comment]
Never mind, I think there's a typo in the manuscript, page 46, where you say `kappa = sin^-1(k)`. I think it should be `kappa / 2 = sin^-1(k)`. Ignore my previous comments if that's the case.

**Comment by rodluger** [comment]
Yep, that was it:
![image](https://user-images.githubusercontent.com/9323819/41204782-e40daf10-6c9d-11e8-83e6-c544a9e06cab.png)
@ericagol can you fix that typo?

**Comment by rodluger** [comment]
@ericagol 
So, I tested it out and the trick of using A and I to compute Q works, but it can be extremely slow to converge because your re-defined `k` is typically much closer to 1 than it is to zero, so the terms in the series solution for `I_vmax` don't start getting small until after a few hundred iterations. But perhaps you were thinking of doing the upward iterations in this case? That might fix the issue.

**Comment by rodluger** [comment]
BTW I verified that the noise floor at 10^-10 is not due to the rotation matrices. It could be due to the evaluation of the Ylms. I'll keep digging.

**Comment by rodluger** [comment]
@ericagol Update on trying out [your expression for Q](https://github.com/rodluger/starry/issues/88#issuecomment-396025079). The series expression for `I_vmax` doesn't seem to converge near ingress for `l = 20` and `r = 110` (my Earth secondary eclipse example), so as I said above downward recursion doesn't work. I tried to do upward recursion, starting with `I_0 = 2 asin(k)`, but that became unstable by the time I got to `l = 20`. I had to fall back to my two-index `H_{u,v}`, which is how I plotted the [figure](https://github.com/rodluger/starry/issues/88#issuecomment-396060716) above. Can you check whether your implementation is stable in this case? It would be nice to do away with `H` (as well as `lambda`) entirely, but it's the only method I am able to get to work currently.

**Comment by ericagol** [comment]
@rodluger Yes, that's a typo;  it should be `\kappa = 2 \sin^{-1} k`, which is written correctly just after D43, but incorrectly after D54; sorry about that!  Fixing it now.

**Comment by ericagol** [comment]
@rodluger Upward recursion seems to work fine for computing `H_v` (for the particular set of parameters I'm using right now).  I am getting larger errors than I would like for small `b` still, which I need to look into.

**Comment by ericagol** [comment]
@rodluger Hmmm...  I'm still getting errors larger than I would like, which seem to be due to `J_v`.  I think the best way to solve this would be with a tridiagonal solver:  compute the `J_0` and `J_{v_max}` terms, and then iterate upwards and downwards, transforming the algebra so that you aren't multiplying by large factors.

**Comment by ericagol** [comment]
@rodluger We should map out where raising/lowering the `v` indices gives better precision.  As I mentioned, I suspect raising will work better for `k^2 ~ 1`, and lowering in small and large `k^2` limits.

**Comment by rodluger** [comment]
Yes, that would be super useful! I can probably code that up in the next few days.
I'm going to keep trying to get a stable upward recursion for Q as above, but so far I've failed. I'll keep you posted.
I haven't coded up the k2>1 case but will do that next.

**Comment by rodluger** [comment]
I didn't quite understand the tridiagonal method: do you mean we simply compute J_v from the top or bottom, whichever is closest?

**Comment by ericagol** [comment]
I mean the following -   write the recursion as:

![image](https://user-images.githubusercontent.com/243664/41209792-99a0047e-6ce2-11e8-9763-e6abbaebb200.jpeg)

Then you have a system of equations going from `J_0` to `J_{v_max}`.  Compute these, and create
a matrix of the coefficients `-\alpha_v`, `1`, `\beta_v`,  multiplying a vector from `J_1` to `J_{v_max - 1}`, and on the right will be a vector with the first element `\alpha_2 J_0` and the last element `\beta_{v_max} J_{v_max}`.   You can then solve this using the [tri-diagonal solver](https://en.wikipedia.org/wiki/Tridiagonal_matrix_algorithm) which involves a forward sweep and backward substitution.  I think this can be arranged to avoid underflow/overflow.

`-\alpha_v J_{v-2} + J_{v-1} - \beta_v J_v = 0\\
\alpha_v = \frac{(2v-3)k^2}{2(v+1) + 2(v-1)k^2}\\
\beta_v = \frac{2v+3}{2(v+1)+2(v-1)k^2}`

**Comment by ericagol** [comment]
In the `k^2 < 1` case, I'm wondering if we just iterate with `k^{1+2v} I_v` and `k^{1+2v} J_v`, if that would be more stable?

**Comment by rodluger** [comment]
@ericagol Can you point me to the code you use to compute `Q` from `A(-0.5)` and `I(beta)`? I still can't get mine to converge for large `l` during eclipse ingress. Here's my Earth occultation plot using your new method (downward iteration for I on the left, upward on the right):
![image](https://user-images.githubusercontent.com/9323819/41247306-7cc5f054-6d62-11e8-9799-16c78255d2fd.png)

The plot on the left makes sense: during ingress, `k^2=((b+1)^2-r^2)/(4b)` is close to 1, so the series solution is very slow to converge. But the upward recursion (right) should work, and yet it goes unstable in almost exactly the same way. I'm wondering if I'm doing something wrong, or if there's some trick to how you defined `kc` or something...

**Comment by ericagol** [comment]
@rodluger It's in `julia/sn_bigr.jl` (although the code is no longer just for large `r`).  I have two functions: `Hv_raise!` and `Hv_lower`.  These both seem to give similar precisions.

**Comment by ericagol** [comment]
@rodluger The only difference with above is how you are computing `Q(G_n)`?

**Comment by rodluger** [comment]
@ericagol I think I found the issue. Look at (D55):
![image](https://user-images.githubusercontent.com/9323819/41249506-3241af58-6d69-11e8-9738-8a73183b8692.png)
If I re-write this to solve for `I_v` in terms of `I_{v-1}`, I get
![image](https://user-images.githubusercontent.com/9323819/41249657-854e53b8-6d69-11e8-8ddb-e34c960f145d.png)
which for `I_1` is equal to `0.5 * I_0 - k * kc`. But in your code for I ([here](https://github.com/rodluger/starry/blob/master/julia/sn_bigr.jl#L101)) and H ([here](https://github.com/rodluger/starry/blob/master/julia/sn_bigr.jl#L222)), it looks like you have `0.5 * I_0 - kc / k`.
Is the error in (D55) or in your code (or in my understanding of it)?

**Comment by rodluger** [comment]
![image](https://user-images.githubusercontent.com/9323819/41250375-9370aaac-6d6b-11e8-87db-22999f673e8e.png)

**Comment by ericagol** [comment]
@rodluger Thanks, good catch, and sorry about the mistake.  Does this fix the computation of `Q`?

**Comment by rodluger** [comment]
@ericagol It doesn't; I coded up my version from the paper, so I didn't have that bug. I suspect that once you fix it you might see the instabilities.

**Comment by ericagol** [comment]
@rodluger But you could go back to the original version of computing `Q` from `H_{uv}`?

**Comment by rodluger** [comment]
That's right, my original version appears to be very stable.

**Comment by rodluger** [comment]
I think so, although I'm still curious about what's causing the instability.
I wonder if this fixes your instabilities for small b?

**Comment by ericagol** [comment]
It doesn't seem to fix the problem for small b.  The problem at small `b` seems to be caused by alternating signs in the terms `A_{i,u,v}`.  I did find an improvement by computing `K_{uv}`, `L_{uv}`, and `Q` by taking the sum of positive and negative terms from least to greatest (each), and then summing the results together;   I think this avoids the round-off error caused by the alternating signs successively cancelling.

**Comment by rodluger** [comment]
So, with the code you just pushed, if I run `test_sn_bigr.jl`with `r = 110` and `b = 110.99`, I get lines that look like this:
```
n: 363 l: 19 m: -17 mu: 36 nu: 2 s: -1.0719823571498716e-21 s_big: -1.201711975110431e-19 d_old: -0.9910795400282887 d_big: -0.9910795400282887
...
n: 371 l: 19 m: -9 mu: 28 nu: 10 s: -2.3841857910483374e-7 s_big: -3.68271397181325e-16 d_old: 6.473991207608575e8 d_big: 6.473991207608575e8
...
n: 375 l: 19 m: -5 mu: 24 nu: 14 s: -1.8426744612576101e-16 s_big: -2.0804086199601594e-14 d_old: -0.9911427281949404 d_big: -0.9911427281949404
...
n: 367 l: 19 m: -13 mu: 32 nu: 6 s: 2.384185791015036e-7 s_big: -6.614199275635531e-18 d_old: -3.604647655331025e10 d_big: -3.604647655331025e10
```
where the difference between `s` and `s_big` is a few orders of magnitude. Curiously, this happens for `l = 19` and `l = 17`, but is much less pronounced for large even `l`. If you switch to the old `H_{u,v}`, these instabilities should disappear.

**Comment by ericagol** [comment]
Okay, thanks!  I still find some large relative errors, but much smaller in the absolute sense:

`n: 291 l: 17 m: -15 mu: 32 nu: 2 s: -6.382340453166007e-18 s_big: -6.734484328137131e-18 d_old: -0.05228965690807874 d_big: -0.05228965690807874
n: 363 l: 19 m: -17 mu: 36 nu: 2 s: 1.9843516557680895e-19 s_big: -1.201711975110431e-19 d_old: -2.651270601331686 d_big: -2.651270601331686
n: 367 l: 19 m: -13 mu: 32 nu: 6 s: -6.846679775031808e-18 s_big: -6.614199275635531e-18 d_old: 0.035148698989559746 d_big: 0.035148698989559746`

**Comment by ericagol** [comment]
Are you happy with this?

**Comment by rodluger** [comment]
I think so, though we should come back to this after I've finished coding everything up in C. Are you sure that the remaining error is still due to `H`?

**Comment by ericagol** [comment]
Sorry, no;  it's due to `K` or `L`, not `H`.

**Comment by rodluger** [comment]
In that case I'm definitely happy with it!

**Comment by rodluger** [comment]
I think there's a typo in (D65):
![image](https://user-images.githubusercontent.com/9323819/41267743-8298356a-6db1-11e8-82a8-082cadc9e105.png)
The factor of 2 shouldn't be there in the `K` term:
![image](https://user-images.githubusercontent.com/9323819/41267717-6933dd5e-6db1-11e8-9d4d-0055ee17d66f.png)

**Comment by rodluger** [comment]
@ericagol We should make it clear in the text that (if I'm not mistaken) the upward and downward recursion expressions for I and J (D55, D56, and D73) are valid in both the `k^2 < 1` and `k^2 >= 1` cases, even though the boundary conditions are different.

**Comment by rodluger** [comment]
@ericagol I think you want your tolerance to be `eps(1/k2)` when `k2 >= 1`:
https://github.com/rodluger/starry/blob/7126d6729a85a3f4f784e93bfea7eb870cce875a/julia/sn_bigr.jl#L87

**Comment by ericagol** [comment]
Maybe!  Can you tell me what `b` and `r` values you use, and whether you are raising/lower the `I_v`, `J_v`, and `H_uv`?

**Comment by rodluger** [comment]
For `r = 0.1`, `b = 1e-8`, `l = 10`, here is the difference between all of the `s` terms computed at double and quadruple precision:
![image](https://user-images.githubusercontent.com/9323819/41311092-2d51a55a-6e38-11e8-98bc-8cdbc987b50b.png)
The relative difference is below machine precision everywhere, although the fractional difference creeps up to `1e-4` when the term is very small: I think that's expected, though. I'm computing `H` with an upward recursion, `I` from the tabulated values, and `J` with a downward recursion.

**Comment by ericagol** [comment]
I get similar looking residuals as you for the same parameters:

![diff_lmax10_r0 1_b1em8](https://user-images.githubusercontent.com/243664/41314779-8f3ff9ce-6e42-11e8-8348-a13ccaab1a95.png)

I'm happy that we've reached machine precision!  Thanks for tracking down the typos - I didn't do as thorough job as I had with the `r>>1` case, so sorry you had to root out the errors.

**Comment by rodluger** [comment]
Nice! And no worries, this is the best way to make sure we're doing the
right thing.

By the way, my criterion for doing upward recursion is 0.5 < k^2 < 2. It
seems to work well everywhere I've tested it. It may be related to the fact
that if the series coefficients are close to unity, 1/2 is the largest
value for which the series converges. Our coefficients drop off with
increasing n, but as a rule of thumb this might make sense...

**Comment by rodluger** [comment]
@ericagol Let me know once you've fixed the typo in (D65) and your `cel` code for `J_0` and `J_1` and I'll close this issue. I've opened new ones with things that came up, so that will help with the organization.

**Comment by ericagol** [comment]
Yes, I've fixed those; thanks!

**Comment by ericagol** [comment]
@rodluger How does the earth occultation look now that you've updated your code?

**Comment by rodluger** [comment]
Really good!
![image](https://user-images.githubusercontent.com/9323819/41483192-ffd70d84-708c-11e8-9bac-5a275c76b150.png)

**Comment by ericagol** [comment]
@rodluger Excellent!
