### ISSUE TITLE
Evaluating `I_v` for `k^2 > 1`

### ISSUE THREAD

**Issue by rodluger** [rodluger/starry#98]
For integer `v`, the expression for `I_v` in the `k^2 > 1` limit
![image](https://user-images.githubusercontent.com/9323819/41302924-a214f8c8-6e20-11e8-8674-a276c899bf27.png)
is just a ratio of Gamma functions:
![image](https://user-images.githubusercontent.com/9323819/41302916-9be8cbc8-6e20-11e8-98f1-c1b5b400f95b.png)
for which [efficient, accurate algorithms](https://www.boost.org/doc/libs/1_60_0/libs/math/doc/html/math_toolkit/sf_gamma/gamma_ratios.html) exist. I'm going to pre-tabulate these up to some large value of `v` at compile-time and compute higher values as needed in run-time.

**Comment by ericagol** [comment]
Sounds great!   Of course these can also be computed recursively with I[0]=\pi and I[v]=I[v-1]*(1-1/(2v)), which should be fast and stable.  Are these algorithms compatible with autodiff?

**Comment by rodluger** [comment]
Well, since `I_v` doesn't depend on `b` or `r` when `ksq >= 1`, the derivative is always zero, no? Shouldn't be a problem for autodiff.

**Comment by ericagol** [comment]
I just tried calling `cel_bulirsch` with `r=0.1` and `b=0.9` yielding `k_c = 0` but `k^2 = 1-small number` and found that it didn't exit the while loop.

**Comment by rodluger** [comment]
Hmm -- it didn't exit the `cel_bulirsch` loop?

**Comment by ericagol** [comment]
Yeah - the parameter `kc` is zero, while `g` stays pinned at `1.0`, so `abs(g-kc)` never decreases below the tolerance, `g*ca`.   I think what I need to do is to check for both `k^2=1` and `kc=1` since round-off error can sometimes cause the sum `k^2+kc^2` to not be equal to one.
