### ISSUE TITLE
cel convergence issues

### ISSUE THREAD

**Issue by rodluger** [rodluger/starry#99]
Moving the discussion of `cel_bulirsch` convergence (#98) here.

**Eric Agol:** I just tried calling `cel_bulirsch` with `r=0.1` and `b=0.9` yielding `k_c = 0` but `k^2 = 1-small number` and found that it didn't exit the while loop. The parameter `kc` is zero, while `g` stays pinned at `1.0`, so `abs(g-kc)` never decreases below the tolerance, `g*ca`.   I think what I need to do is to check for both `k^2=1` and `kc=1` since round-off error can sometimes cause the sum `k^2+kc^2` to not be equal to one.

**Comment by rodluger** [comment]
@ericagol I confirm that the elliptic integral does not converge when `b + r = 1` in general.

**Comment by ericagol** [comment]
I fixed this by setting `kc=eps(k2)` when `k^2=1` or `kc = 0`.
